examples/Bin.re, src/UI/FontCache.re, src/UI/Style.re, src/UI/TextNode.re
__Issue:__ Previous, we were loading fonts every frame. This is already expensive since we load them both in `harfbuzz` and `freetype`.
__Fix:__ Cache the loaded fonts so we don't keep reloading them.
=> Add caching for fonts

esy.json
__Issue:__ The backspace key doesn't clear the final character.
Repro:
- Run `AutoComplete.exe`
- Press `a`
- Press `backspace`
Expected: Input should be clear
Actual: `a` is still hanging around
__Defect:__ This was a bug in `reason-reactify` - not properly comparing primitives in this case. That resulted in `updateInstance` not being called in our reconciler on the clear.
__Fix:__ This was fixed in bryphe/reason-reactify#22, and this change just pulls in a newer version.
=> Bugfix: Backspace doesn't totally clear input box

src/Core/App.re, src/Core/Performance.re, src/Core/Revery_Core.re, src/Core/Window.re, src/UI/Assets.re, src/UI/ImageNode.re, src/UI/Revery_UI.re, src/UI/TextNode.re, src/UI/ViewNode.re
This fixes several low-hanging performance issues:
- We were rendering cubes (!!) instead of quads for all the geometry
- We were recompiling shaders used in the UI every frame
- We would resize the window while in the middle of rendering - this was problematic for both performance causing stretching artifacts.
I was also experimenting with the impact of vsync on performance, so there is now an option on the window to enable / disable vsync (this can be overridden by driver settings though).
TODO:
=> Performance: Fix some low-hanging fruit

examples/Autocomplete.re
When the input string is empty and backspace is hit, you get the error: 
`Fatal error: exception Invalid_argument("String.sub / Bytes.sub")`
This is due negative index passed to substring.
=> fix crash in example with empty string

examples/Bin.re, src/UI/FontShader.re, src/UI/ImageNode.re, src/UI/RenderPass.re, src/UI/Revery_UI.re, src/UI/TextNode.re, src/UI/ViewNode.re
__Issue:__ Text is _always_ rendered with a black background, as described in #57 (thanks @Akin909 for logging the issue and the screenshot).
__Defect:__ By default, [alpha blending](https://www.opengl.org/archives/resources/faq/technical/transparency.htm) is off in OpenGL/WebGL. We were actually turning it on for rendering images, but that was it.
__Fix:__ Set up a 'two-pass' rendering system. The first pass renders all solid / opaque objects without transparency. This is a common technique to populate the z-buffer so that we can minimize the more expensive alpha-blended pixels. The second pass renders transparent objects. The `glEnable(GL_BLEND)` and `glBlendFunc` were moved out of the Image node and into a higher-level pass (this minimizes state transitions).
I anticipate this will …
=> Fix #57: Add an alpha pass to render non-opaque items

examples/Bin.re, src/Geometry/Quad.re, src/UI/FontRenderer.re, src/UI/FontShader.re, src/UI/ImageNode.re, src/UI/Node.re, src/UI/SolidShader.re, src/UI/TextNode.re, src/UI/TextureShader.re, src/UI/ViewNode.re
__Issue:__ We were using some kind of hacky logic to derive vertex positions from texture coordinates for positioning items. This worked, but isn't extensible for a transform pipeline (for example, implementing animations). 
The problem with integrating animations or other functionality is that, sometimes, we want to apply a transform prior to applying the translation into UI / window space - but we don't have that option here, because that implict transformation that happens is always the first thing applied.
__Fix:__ Refactor to use the actual quad positions, which are centered on the origin - meaning we can apply animations that prior to applying transforms into UI/window space.
=> Refactoring: Use local transforms

.ci/esy-build-steps.yml, package.json, src/Core/Revery_Core.re, src/UI/FontRenderer.re, src/UI/TextNode.re, test/Core/MemoizeTests.re, test/Core/dune, test/Test.re, test/TestRunner.re, test/dune
__Issue:__ When rendering a `TextNode`, we are always round-tripping the character to fontkit to render (and allocating a new glBuffer and everything to boot) - this is bad for both performance and memory.
__Fix:__ Memoize / cache these characters. Eventually, we should expand this to support texture atlases for characters.
=> Bugfix / Performance: Memory leak - always allocating new memory for font characters

package.json
Fixes error when bringing `revery` in as a dependency: 
```
ERROR  C:/Users/bryph/.esy/3_/i/revery-eef9eaab/lib\Revery\META:1 0-0
1 ┆ version = "dev"
2 ┆ description = ""
3 ┆ requires = "Revery_Core
4 ┆             Revery_Geometry
```
=> Add Revery_Math to install step

src/UI/ImageNode.re, src/UI/Node.re, src/UI/NodeDrawContext.re, src/UI/Revery_UI.re, src/UI/TextNode.re, src/UI/ViewNode.re
Currently, we were only using the `worldTransform` (the result of multiplying all parent transforms) in the `draw` method. However, we also need this concept when doing hit testing.
The idea is that we use the `worldTransform` to calculate the axis-aligned bounding box in screen-space (the rectangle encompassing the element), and then check to see if the mouse position is within that AABB. 
This means that we need to decouple it from just rendering and make it available elsewhere.
=> Hit Testing - Refactoring: Make world transform available outside of draw

src/Core/App.re, src/Core/Color.re, src/Core/Environment.re, src/Core/Revery_Core.re, src/Core/Time.re, src/Shaders/Shader.re, src/Shaders/dune
__Issue:__ When running in the WebGL strategy, the JS execution fails
__Defect:__ There's no platform stub for the sleep call, and it doesn't make sense in the JS world.
__Fix:__ Create an abstraction for sleep, and only execute Unix.sleep on native / bytecode environments.
=> WebGL Compatibility: Remove 'sleep'

examples/Bin.re, src/Geometry/Quad.re, src/UI/Assets.re, src/UI/ImageNode.re, src/UI/Node.re, src/UI/Transform.re, src/UI/Transform.rei, src/UI/ViewNode.re
This refactoring consolidates the __transform__ concepts. Each Node has a `worldTransform` (which is the combined matrix for getting a quad into screen space - incorporating the full chain of parent transforms), and a local transform `transform` (the left/top offset, and any `Transform`'s applied).
This means that transforms are properly chained (ie, before, they did not impact text elements) - parent transforms get applied to nested transforms.
One thing that was also confusing before is that we always used a Quad with corners at `-0.5, -0.5 -> 0.5, 0.5`. If a UI element was 200x400, we would have to apply both a _translation_ and _scale_ transform. This was extra awkward because we would apply the scale, _animations_, and then translation - hard to reason about how this should be hooked …
=> Refactoring: Clean up geometry / transforms

src/UI/FontRenderer.re
Font rendering looks much better with proper texture wrap settings:
vs
=> Fix #94 - Use GL_CLAMP_TO_EDGE for font rendering

src/UI/Layout.re, src/UI/Node.re, src/UI/Revery_UI.re, test/UI/NodeTests.re, test/UI/Tests.re, test/UI/dune
This implements a `hitTest` function on `node` which returns `true` if a point is within a node's bounding box, taking into account upstream parent transforms.
This is an important  pre-requisite for mouse input - since we need to know which node(s) the cursor is over so that we can properly dispatch events to the UI.
=> Input - Mouse: Initial hitTest implementation

README.md, examples/Autocomplete.re, examples/Bin.re, examples/Flexbox.re, src/UI/Revery_UI.re
__Issue:__ Spinning up a UI is too complicated. Consumers of `revery` shouldn't need to know / care about the under-the-hood render callback provided by `glfw`.
__Fix:__ Consolidate `UI.create`/`UI.render` into `UI.start`, which just takes a callback that returns UI components.
Some things to think about in the future - do we want to pass any context in this render callback? For example - current app state, viewport / window dimensions, etc? All of this is accessible via the closure but perhaps there are some benefits to encapsulating these as args.
=> API: Simplify UI creation

examples/Bin.re, src/UI/Animation.re, test/UI/AnimationTest.re
__Issue:__ The `delay` for an animation wasn't being accounted for correctly. We weren't including the `delay` in the `endTime` calculation, so the animation would just end up being shortened by the dealy.
__Fix:__ Incorporate delay in local time calculation. Add test that exercises bug.
=> Animation - Bug: Fix timing when delay is present

examples/Autocomplete.re, examples/Bin.re, package.json, src/Core/Color_wrapper.re, src/Core/Events.re, src/Core/MouseButton.re, src/Core/MouseButton.rei, src/Core/Revery_Core.re, src/Core/Window.re, src/UI/Layout.re, src/UI/Mouse.re, src/UI/Node.re, src/UI/NodeEvents.re, src/UI/Primitives.re, src/UI/Revery_UI.re, src/UI/UiReconciler.re, test/UI/MouseTest.re
This wires up the GLFW mouse events to the hit testing that was implemented in #87 , and exposes them in our `<view />` primitive.
This is a stepping stone, but gets us closer to having first-class `<Button />`, `<Slider />`, `<Scrollbar />` components.
__TODO:__
=> #38 - Part 2 - Hook up some basic mouseup/mousedown/mousemove events

src/Core/Window.re
__Issue:__ Maximizing (or even just resizing) the window completely breaks rendering - this is easy to see with the `Bin.exe` example - if you maximize or resize, you'll just get an empty screen.
__Defect:__ We weren't properly setting width/height/framebufferWidth/framebufferHeight in the callbacks.
__Fix:__
- For the `glfwSetFramebufferSizeCallback`, we set the `framebufferWidth/framebufferHeight` properties
- For the `glfwSetWindowSizeCallback`, set the `width/height` properties
This is an important distinction, because the window size is not always at a 1-to-1 ratio with the framebuffer size (for example, high-dpi displays).
=> Bugfix: Fix issue where maximizing / resizing window breaks rendering

README.md
I was tried to run examples from this repository yesterday. I faced the problem with running it on my `macOS` (endless build step :D). 
I solved this by preinstalling some libs. Big thanks to @bryphe and @ulrikstrid for help.
The second problem was with a path for built examples.
=> [DOC] Add information for mac users

src/UI/Revery_UI.re
Tiny fix for retina displays where the size of the root node wasn't taking `pixelRatio` into account.
Before:
After:
=> Fix autosize=false in retina

src/UI/Node.re, src/UI/NodeEvents.re, src/UI/Primitives.re
Small enhancement that leverages the language + JSX transform to make the `onMouse*` props really optional. This allows to remove the noop from `NodeEvents` but more importantly it avoids to perform all those noop calls for elements that don't set any event listeners, which removes some overhead (not sure really how much impact it would have in performance, but every little step counts! 😄 ).
From the users / API perspective, nothing changes (i.e. they can still pass raw callbacks to `onMouse*` props without the need to wrap these callbacks with `Some`).
=> Treat mouse events as optional

src/UI/Revery_UI.re
Fixes #146.
Just getting the ball rolling, this seems to work and fix the original issue, but I'm not convinced about this solution as it feels wrong to pass raw dimensions in the events, when everything else is not using the raw dimensions. However, I tried the alternate approach of adjusting the dimensions in `Node#hitTest` but it didn't work as I expected. Maybe it's because of this call to `getWorldTransform`?
https://github.com/jchavarri/revery/blob/3a0ef1a123312c6ff396efa76e8c72d285c8bb32/src/UI/Node.re#L66
=> Fix hit test retina

src/UI/ViewNode.re
Quick fix for #145 -- couldn't get it to compile locally so this isn't tested yet. After pulling from upstream I keep getting the following error:
```
File "src/Core/Window.re", line 307, characters 30-52:                                                                                                                                              
Error: Unbound value Glfw.glfwDestroyWindow             
```
Tried to reinstall reason-glfw but I think this might be because of changes to the development version that haven't been pushed to NPM.
=> Fix border rendering in transparent views

src/Core/Environment.re, src/UI/FontCache.re, src/UI/ImageRenderer.re
Fixes #141 @bryphe hopefully this addresses the problem of loading fonts and images using `esy x Bin` (tested and does work) in the way you intended
=> load images and fonts from executing dir

src/UI/FontRenderer.re, src/UI/TextNode.re
fixes #115, memoizes the fn in a similar way as the `getTexture` function
=> Memoize fontkit.fk_shape

examples/Bin.re, src/UI/Animation.re, test/UI/AnimationTest.re
@bryphe 
Progress update:
1) Test in AnimationTest.re does not actually change any of the other tests, only adds the quadratic one. I went back and checked this twice myself.
2) oneDimBezier alone is not enough to fully recreate the variety of css easing functions, but I'm 98% certain that a true bezier cubic could be made using [x,y] as a pair of oneDimBezier, then some math, then we can copy every CSS easing function offered.
3) New PR to get this all off of master and on to a feature branch :)
=> Add simple easing functions

.gitignore, README.md, package.json
Same as https://github.com/bryphe/reason-reactify/pull/32 but for `revery`.
Not sure about the paths in README as I don't have a Windows machine, but happy to fix them if they're wrong. 🙂
=> Remove buildsInSource

package.json
__Issue:__ `ocamlmerlin-reason` crashes on Windows due to https://github.com/facebook/reason/pull/2256
__Fix:__ Bring in a newer `reason` to work around this until a new official version is released.
=> Dependency: Pin to newer facebook/reason

src/UI/Revery_UI.re
__Issue:__ If a component calls `setState`, the UI does not get refreshed in response. This is very problematic for a UI, since the interesting interactivity will occur duet o state transitions.
__Defect:__ Our `setShouldRenderCallback` should be smarter - as pointed out in #170 by @OhadRau , there are additional cases we need to handle here.
__Fix:__ The `reason-reactify` reconciler was intended to help with this. It exposes both a `onBeginReconcile` and `onEndReconcile` events that are dispatched whenever a sub-tree is updated. For example, if you call `setState(...)` from some component, that event will be dispatched with the target node as the first argument. For now, we set a `dirty` flag to `true`, and clear that `dirty` flag on render.
There's a test case in `reason-reactify` that …
=> Fix #170 - set a 'dirty' flag in response to reconciliation

package.json
__Issue:__ When using `revery` as a dependency, this error is hit:
```
```
__Fix:__ Add `esy-installer` step for `Revery_UI_Components`
=> Bugfix: Add missed install step for Revery_UI_Components

.ci/esy-build-steps.yml
This adds a quick check after `esy install` that there are no unstaged changes - if there are, it means the lockfile needs to be updated. This will help keep the `esy.lock` dir from getting too far out-of-date.
=> CI: Enforce lock directory is up-to-date in CI

src/Core/Window.re
This was a regression caught by @jchavarri in #190 - thanks for catching that! Had an unnecessary `glfwSetWindowSize` call which is no longer necessary (was used while developing to trigger a window-size change callback), but now because we're using `glfwGetWindowSize` to get the window size explicitly, there's no need for it.
=> Bugfix: Remove unnecessary glfwSetWindowSize call

examples/Hello.re, src/Core/Events.re, src/Core/MouseCursors.re, src/Core/Window.re, src/UI/Mouse.re, src/UI/Mouse.rei, src/UI/Node.re, src/UI/NodeEvents.re, src/UI/Primitives.re, src/UI/Revery_UI.re
This adds an `onMouseWheel` event to the primitives. This will be helpful for some of the `<ScrollView />` work happening, like in #195 . 
This does the following:
- Subscribe a callback to the `glfwSetScroll` and add a `onMouseWheel` event to the `Window.t` object
- Listen to the `onMouseWheel` event in `Revery.UI` and dispatch an `onMouseWheel` event for the UI tree to respond to
- Hook up the `onMouseWheel` to the primitives so consumers of the API can listen to it via `<view onMouseWheel={(evt) => ...} />`
=> Input: Add mousewheel event

src/UI/Node.re, src/UI/UiRender.re, test/UI/MouseTest.re, test/UI/NodeTests.re
__Issue:__ One of the first performance bottlenecks with #212 is excessive amounts of garbage + matrix multiplication. Our matrix multiplication pipeline (getting the `worldTransform` and `transform`) is wholly unoptimized and _always_ recalculates on every request, and the `worldTransform` needs to be calculated based on the entire chain - so this can blow up to be a pretty huge number of matrix multiplications! 
In addition, generating the `worldTransform` is a function of `localTransform` * `parent.worldTransform`, and the local transform _itself_ takes multiple matrix multiplications.
This calculation happens for rendering, as well as for hit testing (getting the bounding box).
This change implements a `recalculate` step where we do all those calculations at once and cache the …
=> Performance Fixes Part 1: Reduce unnecessary matrix multiplications

src/Core/App.re, src/Core/GarbageCollector.re, src/Core/Performance.re
__Issue:__ The current strategy we use for the GC isn't really amenable for real-time, animated apps like we want to build with Revery. For real-time apps, we don't want to get surprise allocations that could kill our render deadline and result in a skipped frame.
We see a lot of GC activity in examples that render a _lot_ of elements (ie, #212)
There's two real options for this:
- __Option 1:__ Never allocate during the course of the app. Pre-allocate ahead of time. Then, GC is never triggered, and you don't have to worry. This option is feasible in some languages like C# or Java by 'pre-allocating' and using 'Recycle Pools', but it's not really feasible in a functional world.
- __Option 2:__ Allocate frequently, but clean up the GC frequently such as to minimize promotions to the major …
=> Performance Fixes - Part 2: GC tuning + profiling

src/UI/Mouse.re, src/UI/Node.re
__Issue:__ Intermittently when starting the example app, get an error like:
```
Fatal error: exception Revery_UI__Node.NoDataException("getBoundingBox")
```
__Defect:__ This is a regression from #216 . We calculate certain properties (`transform`, `worldTransform`, `bbox`, etc) during rendering. Prior to the first render - these properties are not available. However, if there is mouse movement, the mouse event can potentially get dispatched prior to the render. The mouse dispatching uses the calculated bbox to figure out if it needs to dispatch an event. In this case - there is a crash occurring because the bounding box hasn't been calculated yet.
__Fix:__ Don't dispatch events until these calculated properties are available.
=> Bugfix: Exception on start

src/Core/App.re
__Issue:__ When idle, the application was still taking up appreciable CPU.
__Defect:__ This was a regression from #217 - we removed a 'sleep' that is used when the application is idle, to limit CPU impact.
__Fix:__ Bring back the removed sleep, and implement a state machine:
- App is running 'real-time' - do a minor collection
- App is transition from 'running' to 'idle' - do a full collection
- App is 'idle' - sleep for 1ms
=> Performance: Improve CPU usage when idle

examples/Slider.re, src/UI_Components/Input.re, src/UI_Components/Slider.re
This implements a `vertical` property for the `Slider` to be able to use the vertical orientation. This is kind of a pre-requisite to scrollbars since I'll be using the `Slider` control for those, initially.
=> Slider: Vertical Orientation

examples/Border.re, examples/Boxshadow.re, examples/Calculator.re, examples/DefaultButton.re, examples/Examples.re, examples/Flexbox.re, examples/Focus.re, examples/GameOfLife.re, examples/Hello.re, examples/InputExample.re, examples/Overflow.re, examples/Slider.re, examples/Stopwatch.re, src/UI/Primitives.re, src/UI/Style.re, src/UI_Components/Button.re, src/UI_Components/Clickable.re, src/UI_Components/Input.re, src/UI_Components/Slider.re, test/UI/StyleTest.re
I was inspired by @wokalski suggestion in #205 idea of a change to the style api that would change it from
```reason
<Text
style=Style.make(
~color=Colors.red
~backgroundColor=Colors.blue
/* a bunch of stuff */
(),
)
/>
```
to 
```reason
<Text
style=[
fontSize(1)
fontFamily(green)
flexDirection(row)
width(percent(90)) /* future plan that can come based on this */
]/>
```
Other examples of similar patterns are `brisk`, `bs-nice` and `bs-css`.
Current implementation so far is heavily inspired by `brisk` :laughing: 
The advantages of this would be a simpler, less error prone to newbie syntax (like forgetting to pass `unit` at the end of the make function) less exposure of the internal api of things like `BoxShadow` so this way it can be re-implemented and a user wouldn't have to refactor …
=> Feature/Update Style API

src/UI/Node.re, src/UI/NodeDrawContext.re, src/UI/TextNode.re, src/UI/UiRender.re
__Issue:__ When shrinking the window (either by dragging to make the window smaller, or pressing the 'restore' button after maximizing), the app would crash with a division-by-zero error.
__Defect:__ During resize, there are some transient states with the resize where we calculate the pixel ratio as `0.99` - the `float_to_int` is a `floor` operation, so when we run `float_to_int(0.99)`, it gets converted to an integer of 0, and then the division operations down the road fail.
__Fix:__ Leave the floating point value and defer conversion until the endpoints. For usages in finding the font size, we need to convert to an integer at that point. For text, though, we can just use the floating point value as-is.
=> Fix #180 - Crash when shrinking window

src/UI_Components/Input.re, src/UI_Components/Slider.re
This adds subtly different styling for the slider 'before' portion of the track and 'after' portion:
=> UI - Slider: Separate styling for 'before' and 'after' track

esy.lock/index.json, package.json
__Issue:__ Freetype2/Harfbuzz fail to build when the `x86_64-w64-mingw32-gcc` toolchain was in the PATH - those packages erroneously assumed if those were in the path, we must be on Windows.
__Fix:__ In the packages:
- `esy-freetype2`: esy-packages/esy-freetype2#d9b9324
- `esy-harfbuzz`: esy-packages/esy-harfbuzz#d1da4da
They both ran a 'test script' to test the compilation out. This really isn't necessary in the main build (should just be a test case). Since that test script is causing problems, removed it from the main build.
This PR just updates deps in the revery repo
=> [WIP] Bugfix: harfbuzz+freetype2 build failure w/ cross-compiler toolchain

esy.lock/index.json, examples/index.html, package.json
__Issue:__ The 'debug' build of our 'Examples.bc.js' (the JavaScript build of our example app) is ~10MB. That would be a quite a lot to expect someone to download!
This adds an `esy build:release` command that uses Dune's release profile to emit a smaller output. After the change, its around ~750KB.
However, there were a few small blockers fixed in this PR and https://github.com/revery-ui/reason-fontkit/pull/17 to enable this.
Have a placeholder site up with an inline demo of our JS+WebGL build (still VERY WIP) - https://5c4a7c5587220f76e47df405--compassionate-aryabhata-b8425c.netlify.com/revery/
=> Enable optimized build output for JS target

esy.lock/index.json, package.json
Similiar issue as #266 , but impacting `esy-glfw`. This brings in the fix for esy-glfw in esy-packages/esy-glfw#1 
This should address the next issue in #209
=> Bugfix: Failure to build GLFW when MingW cross-compiler toolchain is present

Revery_Native.opam, esy.lock/index.json, examples/Examples.re, examples/Native.re, package.json, src/Native/Dialog.re, src/Native/ReveryCocoa.h, src/Native/ReveryWin32.h, src/Native/Revery_Native.re, src/Native/config/discover.ml, src/Native/config/dune, src/Native/dialog.c, src/Native/dialog.cpp, src/Native/dialog.js, src/Native/dialog_cocoa.c, src/Native/dialog_win32.c, src/Native/dune, src/Platform.re, src/Revery.re, src/dune
This is a proposal for how we could (potentially) implement a native layer for Revery, re #250 #249 
This adds a `Revery_Native` module (which actually talks to the native Win32/Cocoa APIs). An open question is how we'll implement support on Linux platforms - what's the best way to handle this in X11? I see some apps "roll their own" platform dialogs, which seems pretty intense. I'm leaving this stubbed out for now, but perhaps someone more knowledgeable than me in X11 can help out.
This is what the 'native' example looks like on Windows:
Also works on OSX (Cocoa) and JS with these changes. The Linux/X11 strategy is just a stub right now.
This depends on the work done in bryphe/reason-glfw#89 to expose a `glfwGetNativeWindow` API, which gives us access to the platform-specific window. …
=> Native Integration: Platform alert dialog

package.json
@bryphe After pulling the latest master branch, I wasn't able to run the examples. I think it's because of the new package you've added, so I've added it to the install list under esy in the package.json.
=> Add missing revery_native.install script

examples/Examples.re
Center the examples window and increase its size to be half of the available window height and width, this is a partial fix for #226
=> Center example container and increase size

src/UI_Components/ScrollView.re
No companion issue. Found while investigating #288.
When the wheel event would return `0.x` we wouldn't move the scroll position. This PR changes the calculation order so that we multiple first by 25 and then round, so every event causes some effect, even if small.
=> Scroll for smaller amounts

src/UI_Components/Clickable.re
Fixes: #227
@bryphe I have a concern about constantly calling `setOpacity` on `mouseMove` (cause it may happen a lot)
https://github.com/revery-ui/revery/pull/296/files#diff-b70d90548201b5505a0a67ee349e4a53R42
Do we need to throttle it maybe, or it's somehow throttled for us?
=> Bugfix: Clickable now tracking its bounds and mouse events appropriately

src/UI_Components/Slider.re
This fixes #342 - slider not updating as mouse moves. Thanks @wokalski for the help troubleshooting and debugging!
This uses the `effect` hook per @wokalski 's suggestion so that the functions for `onMouseMove` and `onMouseUp` always have the latest variables provided by the hooks (so they never call a stale setter)
=> Fix #342: Slider not updating values as mouse moves

README.md
This is to prevent any issues in the future, like #339 with Fedora 28. @bryphe noted that this could also be fixed with linker flags, but I think this is a good (temporary) solution.
=> Add harfbuzz to list of dependencies and a note about the minimum required version

src/UI/TextNode.re
There were a couple of issues with text-rendering on high-dpi displays. These stem from the fact that if the `pixelRatio` is `2`, `3`, we actually request a glyph thats 2x or 3x bigger than the screen-space coordinates - otherwise, we'll end up with a font glyph that is low-resolution. On a Macbook retina display, for example, if our screen-space Window is 800x600, it might actually have a framebuffer size of 1600x1200 or 2400x1800. 
Then, if we render a glyph for font size 14px, we actually want to render it at either a 28px or 42px size, so we get the full glyph resolution. This is challenging for layout because it means the font metrics we get are actually scaled up, which we actually have to scale back down by dividing by the pixel ratio.
__Fixes:__
1) The `lineHeightPx` method wasn't …
=> Fix #347: High-dpi display text rendering issues

examples/Autocomplete.re, src/UI/Revery_UI.re, src/UI/UiContainer.re, src/UI/UiRender.re
This removes the `autoSize` option from the UI. This simplifies the layout / rendering aspect. The feature was only used in the `Autocomplete` example but isn't used anywhere else - and there were a few issues with it. 
With GLFW 3.3, there will be a better way to handle this scenario - there's support for window transparency and framebuffer transparency, which will be a more robust way to create overlay-style apps that change size.
=> Cleanup: Remove autosize

examples/AnalogClock.re, examples/Autocomplete.re, examples/Border.re, examples/Boxshadow.re, examples/Calculator.re, examples/CheckboxExample.re, examples/DefaultButton.re, examples/Examples.re, examples/Flexbox.re, examples/Focus.re, examples/GameOfLife.re, examples/Hello.re, examples/HoverExample.re, examples/InputExample.re, examples/RadioButtonExample.re, examples/ScreenCapture.re, examples/ScrollView.re, examples/Slider.re, examples/Stopwatch.re, examples/TextExample.re, examples/TodoExample.re, examples/TreeView.re, src/Revery.re
The `Revery.Core` vs `Revery` module is confusing - it's not clear when to `open Revery` or `open Revery.Core`. 
This change moves the entirety of `Revery.Core` into `Revery`, to remove that confusion.
=> API: Move 'Revery.Core' into 'Revery'

src/UI/Style.re, src/UI_Components/Dropdown.re, src/UI_Components/Input.re, src/UI_Components/ScrollView.re
Most of our style properties use polymorphic variants now, like `Style.[position('Absolute)]`. However, `overflow` was still using the `LayoutTypes` which is confusing and not very discoverable. This switches the `overflow` style property to use the polymorphic variant style.
=> API: Use polymorphic variant for Overflow

src/UI/Primitives.re
This enables the use of the `key` property to help give the reconciler hints about reusing particular elements.
=> Performance: Add key to primitive elements

src/UI/Node.re
If the layout style hasn't changed - don't keep re-generating it. This helps in the case where the render tree hasn't changed and the style is constant - we were always re-generating the layout style, but this isn't necessary. 
Improves the performance of our `Layout: layout node tree (4 deep, 4 wide)` test:
__BEFORE:__
```
+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
|  BENCHMARK                                                   |  TIME              |  MINOR GC  |  MAJOR GC  |  MINOR ALLOC  |  PROMOTED   |  MAJOR ALLOC  |
|--------------------------------------------------------------+--------------------+------------+------------+---------------+-------------+---------------| …
```
=> Performance: Don't recreate style for layout, if it hasn't changed

src/Draw/RenderPass.re, src/Draw/Revery_Draw.re, src/Draw/Text.re, src/Draw/TextRenderer.re, src/UI/Revery_UI.re, src/UI/TextNode.re
This extracts most of the guts of the `TextNode` into `Revery.Draw.Text`, with methods like:
- `drawString`
- `measure`
- `getLineHeight`
This simplifies the `TextNode` proper, and also this logic to be reused once the immediate-mode rendering node is added (for fast text rendering w/o needing layout or reconciliation). Extension of #374 
TODO:
=> Refactoring: Move text rendering to Draw module

bench/lib/LayoutBench.re, src/UI/Layout.re, src/UI/Node.re, src/UI/Revery_UI.re, src/UI/TextNode.re, src/UI/UiRender.re, test/UI/MouseTest.re, test/UI/NodeTests.re, test/UI/ReconcilerTests.re
__Issue:__ Layout performance is a bottleneck for Revery as applications grow (like our Example app) - it's easy to see in our JS sandbox - every frame triggers layout.
__Defect:__ We currently have a very naive layout strategy.... we re-layout the entire application every frame. We've been able to get away with this so far, by virtue of the speed of the technology and the `flex` library, but it won't scale to more complex applications.
__Fix:__ This implements an incremental layout, where we only bother re-laying out items if a layout style property has changed. This presents a large performance increase, especially in cases where we're animating with only things like transform properties (in which case layout won't be triggered at all).
This is an iteration on some of the work done …
=> Performance: Layout subtree

src/Draw/FontShader.re
Thanks @tcoopman for catching this!
__Issue:__ Some examples would crash with:
```
Fatal error: exception Revery_Shaders__Shader.ShaderCompilationException("0:9(2): error: initializer of type float cannot be assigned to variable of type vec4\n0:16(2): error: initializer of type vec4 cannot be assigned to variable of type float\n0:17(2): error: initializer of type vec4 cannot be assigned to variable of type float\n0:18(2): error: initializer of type vec4 cannot be assigned to variable of type float\n")
```
__Defect:__ In cases where we use correct gamma-corrected text (ie, when there is a solid background color), the shader compilation would crash. This was a bug in the shader - we were trying to assign a `float` to a `vec4` and the shader complains. Some platforms handle this differently …
=> Bugfix: Fix crash in gamma corrected text shader

examples/Examples.re, examples/OpenGLExample.re, src/UI/OpenGLNode.re, src/UI/Primitives.re
This change starts an `<OpenGL />` node that enables a user to drop-out of the reconciler tree and switch to immediate-mode rendering for part of the subtree. This saves performance in both reconciliation and layout when there are purely graphical components to render.
The usage is like:
```
<View style=containerStyle>
<OpenGL
style=outerBox
render={(_, _) => {
glClearColor(1.0, 0.0, 0.0, 1.0);
}} />
</View>
```
And added an example that also does some text rendering.
I'm planning on leveraging this in Oni2 to draw both the buffer window and the minimap, to maximize performance and avoid overhead related to reconciliation / layout for those pieces (which aren't really need anyway!)
In the future - we'll want to also have a way to initialize and dispose graphical resources (buffers, …
=> Performance: Add a node that enables direct access to OpenGL rendering

src/Core/GarbageCollector.re
Profiling Oni2 - we were hitting cases where we'd get surprise collections while scrolling through the buffer.
OCaml's GC has a unique feature where it allows amortized major collections - the `Gc.major_slice` call lets you do a minor collection _and_ a slice of a major collection. We've set up the default to amortize this cost across 60 frames. This helps give us more predictability in major collections and stave off surprising collections (the downside is there is a bit more fixed cost per frame, but it's still <1ms in general).
It's still important to minimize allocations in hot paths, but this helps keep us from hitting as many major allocations for now.
=> GC: Use 'major_slice' instead of 'minor'

examples/OpenGLExample.re, src/Draw/FontShader.re, src/Draw/GradientShader.re, src/Draw/Revery_Draw.re, src/Draw/Shapes.re, src/Draw/SolidShader.re, src/Draw/Text.re, src/Draw/TextureShader.re, src/Geometry/Builder.re, src/Geometry/Geometry.re, src/Geometry/Quad.re, src/Geometry/Triangle.re, src/Geometry/VertexBuffer.re, src/Shaders/BasicShader.re, src/Shaders/CompiledShader.re, src/Shaders/Revery_Shaders.re, src/Shaders/Shader.re, src/Shaders/Types.re, src/UI/ImageNode.re, src/UI/ViewNode.re
__Issue:__ One performance bottleneck we have remaining with lots of draws is setting _uniforms_ (shader parameters). The issue is that, every time we'd set up a shader uniform, we'd need to look up the location in a hash table.
This really isn't necessary - we can look these up once when we compile the shader, and then use them during rendering. Setting shader attributes happens quite a bit, especially since we don't do a good job batching draw calls right now (a next step performance optimization).
This updates each of our built-in shaders to cache the shader uniforms, and make those available. This also updates dependent code paths to use these cached uniforms instead of the string variant (and updates the call to `CompiledShader.setUniformX` to just be a pass-through).
I also …
=> Performance: Cache uniform locations instead of Dictionary lookups

src/UI/TextNode.re
A few questions:
- Should the fixed text be cropped to its dimensions?
- Should I add a test for this? If so, how?
=> Fix #357: TextNode: render text when dimensions are specified

src/UI/ViewNode.re
This switches our ViewNode background drawing from manually making OpenGL calls to using `Shapes.drawRect`. The previous strategy uses `Assets.quad(...)` which isn't very efficient - it uses a hashtable to look-up an existing quad, or creates one. This is especially noticeable in the JSOO builds, where the Hashtable `find_opt` call shows up in performance profiles - but it also impacts native builds, too.
`Shapes.drawRect` is faster - it just uses the unit quad and incorporates the correct transform. It also makes the background drawing code simpler.
=> Performance: ViewNode background drawing

README.md
This fix includes the advice from two issues:
https://github.com/revery-ui/revery/issues/316#issuecomment-462505096
and 
https://github.com/revery-ui/revery/issues/339 (which is not only an issue with Fedora but also ubuntu <= 18.04 - https://www.ubuntuupdates.org/package_metas?utf8=%E2%9C%93&q=harfbuzz)
=> Add notes in readme about ubuntu install issues.

src/Draw/FontShader.re, src/Draw/Text.re, src/UI/TextNode.re
__Issue:__ Even if a background/foreground color is specified, if there is transparency from the parent context, the text rendering would still take the degraded non-gamma-corrected path.
__Defect:__ We'd always multiply the parentContext's opacity into the foreground/background colors, and then use that to decide if we should take the gamma-corrected route or not. 
__Fix:__ When there is parent opacity, we'll apply it after doing the alpha blending of the text in linear space. This is better than the previous experience, where we wouldn't render with gamma correction at all if there was an opacity in the hierarchy.
=> Bugfix: Improve text rendering when parent context has transparency

src/UI/Style.re
This adds a few additional style properties:
- `minWidth`
- `maxWidth`
- `minHeight`
- `maxHeight`
These are already supported by [`flex`](https://github.com/jordwalke/flex), so it is just a matter of wiring it up from our `Style` module.
=> Style / Layout: Add minWidth, maxWidth, minHeight, maxHeight

src/Core/Window.re
__Issue:__ Prior to rendering, the `devicePixelRatio` and `scaleFactor` metrics for the window are not correct.
__Defect:__ We used placeholder values until actually measuring.
__Fix:__ Get those metrics immediately on Window creation.
=> Bugfix - Core: Window devicePixelRatio/scaleFactor

src/Core/App.re, src/Core/Lwt_integration.re
This transparently hooks up the `Lwt` event loop in Revery's app loop. This means that Lwt-based libraries no longer need `Lwt_main.run` - this happens implicitly when creating a Revery app.
This should help to enable scenarios like making async HTTP requests, File I/O requests, etc without blocking the app loop. A work-in-progress example of this is https://github.com/revery-ui/revery-fetch - a `fetch`-like API that works in both the browser via JSOO and native reasonml
=> Feature: Lwt engine integration

src/Draw/Text.re, src/UI/TextNode.re
Thanks @CrossR for catching and reporting this!
__Issue:__ The `revery-quick-start` text was no longer 'fading in' in latest Revery builds. The opacity is always set to `1` when drawing.
__Defect:__ When we refactored the text to use the `Draw` module and split into a default and gamma corrected shader, we did not use the correct opacity value. We only considered the parent's opacity but not the opacity set on the style.
__Fix:__ Incorporate `style.opacity` in final opacity calculation when rendering the text.
=> Bugfix: TextNode opacity from style is not correct

src/Draw/RenderPass.re, src/Draw/Shapes.re, src/Draw/Text.re, src/UI/ImageNode.re, src/UI/Node.re, src/UI/Render.re, src/UI/ViewNode.re
__Issue:__ We do two render-passes across nodes - one for Solid rendering and one for Alpha blending. The original intention with this was to eliminate _overdraw_ (alpha blending is expensive - so if a pixel has a solid value with a higher z-index, we can avoid that cost). However, our current rendering pipeline only does work during the Alpha phase - meaning the traversing and work we do during the Solid is essentially wasted (and even though we don't draw - we make several GL calls, still).
__Fix:__ For now, remove this unused pass. We can revisit splitting these at some point if we see overdraw as a bottleneck.
=> Performance: Remove extra render pass

bench/lib/LayoutBench.re, src/UI/Layout.re, src/UI/Node.re, src/UI/Style.re
An experimental 'minimal layout mode' was added to try and squeeze extra performance out for Onivim 2 (where we were running layout on every node in the minimap and text). However, we ended up delegating those pieces to use the `<OpenGL />` node - so it seems like the 'minimal' layout mode was too niche to be useful (and just adds complexity).
I'd like to explore, though, the flutter-like idea of having nodes control child layout - I think that design is really interesting. Pulling this out means a little less complexity when we go to implement / explore that piece.
=> Refactoring: Remove minimal layout mode

src/UI/ImageNode.re
For the interactive playground, part of the rendering happens in a Worker. When `ImageNode`'s are created - they try and grab a shader / OpenGL texture. We should defer that until actual rendering to allow the node hierarchy to exist in the worker.
=> ImageNode: Move GPU operations to draw method

examples/Examples.re, src/Core/App.re, src/Core/GarbageCollector.re
Thanks @jaredly for reporting this!
__Issue:__ Even for a very bare-bones Revery app, memory usage would climb to ~90-100 MB slowly. This isn't much better than Electron!
__Defect:__ We added in some opinionated garbage collector tuning that seemed to be the culprit - inspired by:  https://md.ekstrandom.net/blog/2010/06/ocaml-memory-tuning However, this had the side effect of letting the minor / major heap grow to that higher size (which isn't desirable in general).
__Fix:__ We'll leave this sort of GC tuning up to the application, instead of baking it into Revery. 
After this fix, the `Examples` app sticks to around ~35MB on Windows, and the example repro app is even less. It seems like we should still be able to do better, but this is progress.
We'll need to investigate a nice way to …
=> Bugfix: Performance - Memory climb on startup

src/Draw/BorderRadiusShader.re
The border radius shader has broken types. I wonder how it compiled before.
=> Fix border radius shader

src/Core/App.re, src/Core/Environment.re, src/Core/file.js
The `Thread.yield` call isn't available in JSOO. This refactors to call the `yield` stub directly, and put a no-op implementation for the JS build.
=> JSOO: Remove Thread.yield

src/Draw/Image.re, src/Draw/ImageRenderer.re, src/Draw/ImageResizeMode.re, src/Draw/Revery_Draw.re, src/UI/ImageNode.re, src/UI/Primitives.re
This adds a `resizeMode` parameter to the `<Image />` primitive, with the following values:
- `Stretch` (default)
- `Repeat` (tile the image to take up the bounds of the component)
The current implementation is very naive and has a few shortcomings:
- Incurs extra draw calls for tiling (it should be only a single draw call)
- Can overlap the bounds of the component (should be trimmed to fit)
=> API: Image - ResizeMode

src/Core/App.re
__Issue:__ For apps that don't have an animation or initial event to trigger a dirty window, the screen will be blank until something triggers a dirty state.
__Defect:__ Previously, before #445 , we had a `needsRender` value on the app instance that was set to `true` on startup, and anytime an action was dispatched against our ad-hoc state management. When that was removed, if nothing triggered a dirty event, a render would never be triggered.
__Fix:__ Always render the first frame. Bring back a limited version of  `needsRender` in the form of `isFirstRender`
=> Bugfix - Regression: PR #445 caused a blank screen on startup

examples/Examples.re, src/Core/App.re, src/Core/Revery_Core.re, src/Core/Window.re, src/Core/WindowCreateOptions.re
__Breaking API Change:__ - this moves the `windowCreateOptions` type to a module, so it's easier to document and more streamlined in picking.
__Before:__
```
~createOptions={	
...Window.defaultCreateOptions,	
width: windowWidth,	
height: windowHeight,	
maximized,	
icon: Some("revery-icon.png"),	
},
```
The problem with this is that `Window.defaultCreateOptions` was not very discoverable...
__After:__
```
~createOptions=
WindowCreateOptions.create(
~width=windowWidth,
~height=windowHeight,
~maximized,
~icon=Some("revery-icon.png"),
(),
),
```
(The `WindowCreateOptions.create` is a bit awkward - perhaps there is a better name for either the module or function?)
=> refactor: Move type windowCreateOptions to module

src/UI/ImageNode.re, src/UI/ImageResizeMode.re, src/UI/Primitives.re, src/UI/Revery_UI.re, src/UI_Components/Container.re, src/UI_Components/Positioned.re, src/UI_Components/Revery_UI_Components.re, src/UI_Components/Stack.re
This is a baby-step towards a compositional-component API (instead of having  an uber-`style`, we use composition of components with discrete responsibilities).
This adds some initial compositional components, loosely correlating to the similarly-named components in the Flutter space:
- `Stack`
- `Container`
- `Positioned`
I also tweaked the `Image` primitive, and added a width/height property directly to it.
Starting with these to simplify my workshop components. Will add some docs shortly 👍
=> Feature - API: Some initial compositional components

src/UI_Components/ClipContainer.re, src/UI_Components/ClipContainer.rei, src/UI_Components/Revery_UI_Components.re, src/index.mld
This adds a `<ClipContainer />` component, which is like a `<Container />`, except it clips the elements (ie, behaves like having `overflow: hidden`)
=> Component: ClipContainer

src/UI_Components/Clickable.re, src/UI_Components/Clickable.rei
I took a stab  at https://github.com/onivim/oni2/issues/322 but found out that it's blocked because onAnyClick isn't exposed anywhere. This PR aims to fix that
=> Clickable: Expose onRightClick and onAnyClick

src/UI_Components/Tree.re
This tests out @r281GQ's idea in https://github.com/onivim/oni2#377 - it looks like there is a bug in the render order of the treeview. We happen to get the very first element rendering at the end of the list.
=> UI - TreeView: Rendering order

src/Core/Environment.re, src/Core/Environment.rei
__Issue:__ In some cases, notably on OSX when bundling as an `.App` folder, the `getExecutingDirectory` function would return `.`. This is problematic because we often use it to figure out where binary-relative resources are.
__Defect:__ In that case, `Sys.argv[0]` just returns `'.'`. 
__Fix:__ In that particular case, `Sys,executable_name` gives us the full path to the executable. We can get the executing directory from that path.
=> Bugfix: getExecutingDirectory returns '.' in some cases

src/Core/Key.re
This looks like the root cause for https://github.com/onivim/oni2/issues/461 - when pressing `Control+[`, we're sending `Control+(` to libvim instead.
=> fix(bug fix): Bracket keys not picked up as expected

examples/Boxshadow.re, examples/InputExample.re, examples/TreeView.re, src/Draw/GradientShader.re, src/UI/Selector.re, src/UI/Style.re, src/UI/ViewNode.re, src/UI_Primitives/BoxShadow.re, src/UI_Primitives/Padding.re, src/UI_Primitives/Revery_UI_Primitives.re
This is a small, incremental change towards #489 - moving the `boxshadow` style to a component.
This also splits out a basic `<Padding />` component - although padding needs some additional properties (`left`, `right`, `top`, `bottom`, `horizontal`, `vertical`...)
=> UI - Primitives: Move boxshadow style to <BoxShadow /> component

src/Core/Key.re
`Key.toString(KEY_TAB` should return `"\t"`, but it just returns an empty string. This was causing issues in resolving the tab key for bindings in Onivim 2.
=> bugfix: Key.toString(KEY_TAB) does not return correct value

examples/DropdownExample.re, examples/RadioButtonExample.re, src/UI_Components/Dropdown.re, src/UI_Components/RadioButtons.re
In a school project, I have a function that translate string to Variant because DropDown only accept string as value.
But value are not dispayed => we could put anything.
So I have made this small patch to allow everybody to put whatever their want in value field.
=> Enable DropDown and RadioButtons components to have generic value.

examples/Examples.re, examples/ZoomExample.re, src/Core/Window.re, src/Draw/RenderPass.re, src/Draw/Text.re, src/UI/Overflow.re, src/UI/Render.re, src/UI/Revery_UI.re, src/UI/Ui.re, src/UI/Ui.rei
This adds  `Window.getZoom(w)` and `Window.setZoom(w, 1.0)` methods - an opportunistic change after looking at #550 
__TODO:__
=> API - Window: Initial zoom API

bench.esy.lock/index.json, doc.esy.lock/index.json, esy.lock/index.json, examples/Examples.re, examples/FontsExample.re, js.esy.lock/index.json, package.json, src/Font/Discovery.re, src/Font/Revery_Font.re, src/Font/dune, src/Revery.re, src/dune, test.esy.lock/index.json
A major limitation of Revery today is that fonts need to be specified via a direct path to a font file (ttf, otf, etc).
This integrates https://github.com/revery-ui/reason-font-manager so that we can now do font discovery - given a font name + some parameters (bold, italic, etc) - we can search and resolve the font.
There is still some work that should be done, like caching results, asynchronous API, and hooking up to the font rendering - but this sets up the foundation for it.
=> API: Font resolution

src/Core/App.re, src/Core/App.rei
Required by https://github.com/onivim/oni2/pull/715 so that we can fully exercise the code.
In that test case, there is some product code that queues up some code to run on the main thread via `Revery.App.runOnMainThread`. However, there is no app started in the test - so the callback never executes.
This adds a way to explicitly flush those queued up calls and enable the test.
=> API - App: Add flushPendingCallbacks API

bench.esy.lock/index.json, bench.esy.lock/opam/dune-configurator.1.0.0/opam, bench.esy.lock/opam/lwt.4.3.0/opam, doc.esy.lock/index.json, doc.esy.lock/opam/dune-configurator.1.0.0/opam, doc.esy.lock/opam/lwt.4.3.0/opam, esy.lock/index.json, esy.lock/opam/dune-configurator.1.0.0/opam, esy.lock/opam/lwt.4.3.0/opam, js.esy.lock/index.json, js.esy.lock/opam/dune-configurator.1.0.0/opam, js.esy.lock/opam/lwt.4.3.0/opam, package.json, test.esy.lock/index.json, test.esy.lock/opam/dune-configurator.1.0.0/opam, test.esy.lock/opam/lwt.4.3.0/opam
Update reason-fontkit to break dependency on GLFW, for #555
=> Dependency: reason-fontkit -> 2.7.0

src/Core/file.js
When compiling with JSOO, via `esy '@js' run`, the `caml_mutex_lock` and `caml_mutex_unlock` stubs are not implemented, which cause a runtime javascript exception when loading.
This adds some no-op stubs - there is no need to implement these in JS, since there are no threads.
=> Bugfix - JS: Fix missed caml_mutex_lock and caml_mutex_unlock stubs

src/Core/Window.re, src/Core/WindowCreateOptions.re
The current strategy of setting `Window.forceScaleFactor` after window creation wasn't useful, and would've added additional complexity - we'd have to re-acquire metrics and resize the Window.
Instead, we should know if we're going to force scaling when we create the window - so this option was moved to `WindowCreateOptions` and then follows the current flow of getting metrics during window creation, which simplifies management of this setting.
=> Bugfix: Move Window.forceScaleFactor to a window option

bench.esy.lock/index.json, doc.esy.lock/index.json, esy.lock/index.json, examples/Examples.re, js.esy.lock/index.json, package.json, src/UI_Hooks/Animation.re, test.esy.lock/index.json
The fix to bring in the latest `brisk-reconciler` didn't have the fix we needed to properly turn off animations: https://github.com/briskml/brisk-reconciler/pull/40
This updates to `brisk-reconciler@0.0.2` which has the fix we need.
=> Bugfix: Idle cpu usage is always 100

src/Core/Color.re, src/Core/dune, src/Draw/FontRenderer.re
There were two issues blocking the JS build:
- The `Str.regexp` module isn't implemented in JSOO - fixed by switching to `re`
- The `GL_NEAREST` option was crashing in shader compilation w/ our WebGL 1 environment - switching to use `GL_LINEAR` in WebGL builds
=> JS: Bugfixes blocking page load

examples/CanQuitExample.re, examples/Examples.re, src/Core/App.re, src/Core/Window.re
This allows the application to set up a `canQuit` callback - this callback will be called when the user tries to exit the app (ie, via the `x` in the Window). If it returns `false` - the app will not close.
This is needed for Onivim 2 so that we can prevent closing in the case where there are unsaved files.
=> API: Window - Add `setCanQuitCallback` API

src/Shaders/Shader.re
...and improve error messages when shader compilation fails. 
Related to:
https://github.com/onivim/oni2/issues/833
=> Bugfix: Explicitly set precision for both vertex/fragment shaders

bench.esy.lock/index.json, doc.esy.lock/index.json, esy.lock/index.json, js.esy.lock/index.json, package.json, test.esy.lock/index.json
This picks up the X11 build fix on Mac by @CrossR  : https://github.com/revery-ui/esy-sdl2
=> Dependency: reason-sdl2 -> 2.10.3006

src/Core/App.re, src/Core/App.rei
__Issue:__ This is a regression from the SDL2 upgrade. We were expecting that we get a 'WindowClosed' event prior to a 'Quit' event - this is true in the case of pressing the 'x' button in the window, but not the case when quitting the app external to a window - like via `Command+Q` in OSX.
__Fix:__ When we get a Quit event, try to close all the windows. In the 'WindowClosed' before, there won't be any windows around - so the logic will behave as before. However, in the `Command+Q` case, the logic will now attempt to close all open windows.
__BREAKING:__ This also hooks up the `App.quit` API to use the `canQuit` logic.
=> Bugfix: Command+Q doesn't quit the application

src/Core/App.re, src/Core/Window.re, src/UI/Ui.re
This is a fix for https://github.com/onivim/oni2/issues/587 - in i3 or some window managers, when the window is presented or switched to, it would be empty - we weren't triggering a re-render.
SDL2 gives an event for this - the `SDL_WINDOW_EXPOSED` (docs: https://wiki.libsdl.org/SDL_WindowEvent). 
The fix is simply to listen for this and re-draw the UI when we get it.
=> Bugfix: Redraw window on Exposed event

src/Core/Window.re
Related to https://github.com/onivim/oni2/issues/850 - there wasn't quite enough info from the logs to diagnose directly
=> Improve logging to help diagnosability when crashing while creating Window

src/Core/App.re
Thanks @mrkishi for catching this! It turns out SDL2 does not allow the screen saver / sleep to  turn on by default (this makes sense for games). We do not want to block screen saver / sleep with Revery, though.
=> Bugfix: Revery doesn't allow application to sleep

src/Core/App.re
This helps decrease CPU usage when idle by using the `waitTimeout` SDL2 method instead of just a random `sleep`. 
In addition, if we get something to run from another thread, we 'wake up' the application from the `waitTimeout`.
=> Perf: Use waitTimeout when idle

src/Core/Tick.re, test/Core/TickTest.re
`Tick.timeout` should schedule a function to be dispatched once; however, there was a bug in which it would never be cleaned up.
=> Bugfix: Tick.timeout not disposing as expected

.ci/esy-build-steps.yml, .ci/esy-check-hygiene.yml, .ci/use-node.yml, azure-pipelines.yml
CI started failing with: 
```
##[section]Starting: Use Node 8.x
==============================================================================
Task         : Node.js tool installer
Description  : Finds or downloads and caches the specified version spec of Node.js and adds it to the PATH
Version      : 0.159.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/node-js
==============================================================================
Downloading: https://nodejs.org/dist/v8.16.2/node-v8.16.2-darwin-x64.tar.gz
Extracting archive
[command]/usr/bin/tar xzC /Users/runner/runners/2.158.0/work/_temp/fe28070c-703f-4e2e-a618-27b57f84255e -f /Users/runner/runners/2.158.0/work/_temp/9026c5fe-cc47-4dd3-9938-db10c2477341 …
```
=> CI: Bump node version

src/UI_Components/ScrollView.re
This fixes an issue with ScrollView where scrolling with the scroll wheel when not overflowing causes the viewport to rapidly "invert" or "jump" from top to bottom. This is because `maxHeight` is calculated to be negative when the content is smaller than the ScrollView. Fixed by clamping to 0.
=> Fix ScrollView freaking out when scrolling without overflow

src/UI_Components/Button.rei, src/index.mld
Button components require a title prop.
=> Docs: title is required for Button usage

src/UI_Primitives/Text.re
I've begun using "Hover"-primitives in projects, but the `Text`-primitive is missing a few mouse-events. I think it makes sense since they're already in the `View`!
```ocaml
// Hover.re
module Text = {
type state =
| Idle
| Hover
| Active;
type action =
| Idle
| Hover
| Active;
let%component make =
(
~text,
~hoverStyles=[],
~activeStyles=[],
~style=[],
~onClick=?,
(),
) => {
let%hook (state, dispatch) =
Hooks.reducer(~initialState=Idle, (action, _state) =>
switch (action) {
| Idle => Idle
| Hover => Hover
| Active => Active
}
);
let currentStyle =
switch (state) {
| Idle => style
| Hover => Style.merge(~source=style, ~target=hoverStyles)
| Active => Style.merge(~source=style, ~target=activeStyles)
};
<Clickable ?onClick>
<Text
onMouseOut={_ => dispatch(Idle)}
onMouseOver={_ => …
```
=> feat: add more mouse-events to Text-primitive

src/UI_Hooks/Revery_UI_Hooks.re
Fixes #647 
Ach, foiled by the naming of `Ref.ref` again!
So what happened was that the `mountCleanup` closure was returned as the dispose function on mount, but that closure would always refer to the initial value of `maybeDispose`, `None`, because it's not an actual `ref`.
Also, it still worked if the condition changes because that called `mountCleanup` directly instead of using a stored closure! So it seemed to work when you paused the logo animation, and it ALSO worked on unmount AFTER having paused and resumed, because that stored the `dispose` function directly, instead of a closure referring to a stale `maybeDispose`.
The solution is to put an ordinary `ref` in a `state` (or `ref`) hook, and to use ti as an ordinary `ref` instead of using the hook setter.
=> Fix #647, timer set on mount not being cleared 

package.json
For Onivim 2, we see intermittent build failures like:
```
error: command failed: 'bash' '-c' 'echo Build complete' (exited with 127)
esy-build-package: exiting with errors above...
```
When building Onivim / Revery on CI.
It seems that it is failing during our `install` step:
```
"install": [	    "install": [
"esy-installer Revery.install",	
"bash -c \"#{os == 'windows' ? 'cp /usr/x86_64-w64-mingw32/sys-root/mingw/bin/*.dll \\'$cur__bin\\'': 'echo Build complete'}\""
]
```
...although it isn't clear why either `bash` or `echo` would give an exit code of 127 (not found). This switches to use bash's no-op operator `:` instead of using `echo` - it also removes some extraneous logging.
=> Build: Intermittent failure with (exited with 127)

src/Core/Revery_Core.re, src/Core/Window.re, src/Core/WindowCreateOptions.re, src/Core/WindowStyles.re
This ties into the newly added `Sdl2.Window.setMacTitlebarTransparent`, which should eventually be expanded to other OSs.
I created a new file, `WindowStyles.re` to house all the styling of windows we may have in the future.
=> Add a titlebar style option

src/UI_Components/ScrollView.re
__Issue:__ This came about from investigating onivim/oni2#946 - Revery would never shift into an 'idle' state, even though nothing was happening with the editor.
I started 'bisecting' the UI - I eventually found if I removed the file explorer, the issue did not repro. I dug further and found that it was only the `<ScrollView />` that caused the issue - if I removed the `<ScrollView />`, the app would downshift into idle.
The `<ScrollView />` chooses an animation strategy based on the animation state (a really neat, functional implementation!):
```
let%hook (actualScrollTop, _bounceAnimationState, resetBouncingAnimation) =
switch (bouncingState) {
| Idle => Hooks.animation(Animation.const(actualScrollTop))
| Bouncing(force) =>
Hooks.animation(
bounceAnimation(~origin=actualScrollTop, …
```
=> Bugfix: Ensure timer stops when the bounce is 'idle'

src/Core/Window.re
Based on the crash described here: https://github.com/onivim/oni2/issues/976 - it seems we're crashing while calling `glGetString`. I suspect an empty string is being returned.
=> Diagnostics: Additional logging around Gl.getString

bench/lib/LayoutBench.re, src/UI/Node.re, src/UI/Reconciler.re, src/UI/UiEvents.re, test/UI/MouseTest.re, test/UI/NodeTests.re
I'm surprised revery works as good as it does just ignoring this. But unfortunately I stumbled across a bug, as I do, which is likely caused by this. I've therefore changed `node#addChild` to insert by position, and removed `_revChildren` as it no longer serves much of a purpose other than to add complexity. I also believe the assumption that elements typically should be appended is wrong. But even if it isn't, an ordinary list is probably the wrong data structure to use here anyway. A double-ended linked list or skip list might be better.
We should probably implement `moveNode` properly as well, and `removeNode` might be made slightly more efficient by using position rather than `id`, but that's probably not all that significant.
There seems to be no significant difference in the …
=> Respect position in reconciler

examples/Examples.re, examples/NativeExample.re, src/Native/Dialog.re, src/Native/ReveryCocoa.h, src/Native/ReveryGtk.h, src/Native/dialog.cpp, src/Native/dialog_cocoa.c, src/Native/dialog_gtk.c, src/Revery.re
**EDIT**: This is now fixed, and there is more information below.
This provides bindings to `NSOpenPanel`. This is in response to #444 by @Et7f3.
I'm _so_ close, but for some reason, I keep getting strange memory errors on any operations on the string(s) returned.
For example, the code
```reason
Console.log("WORKS:");
Console.log(x);
Console.log("CRASHES:");
Console.log("" ++ x);
```
results in
Hopefully some fresh eyes can help with this.
@Et7f3, any help would be greatly appreciated!
=> [Native] Implement the macOS/Cocoa and Gtk File Dialogs

src/Draw/Text.re, src/UI/TextNode.re, src/UI_Components/Input.re
Tracking fix for root cause of https://github.com/onivim/oni2/issues/1068
For some of the text measurement APIs, we were not taking into account the scaling done for retina displays. This corrects the measurements, so that the `Text.measure` and `Text.getLineHeight` receive accurate metrics when in high-DPI.
=> Bugfix: High-DPI text measurement issue

src/Native/dialog.c
Previously this function was called "revery_alertOpenFiles_bytcode" which would result in a build failure using the bytecode backend
=> Native/dialog.c: Rename "revery_alertOpenFiles_bytcode" to "revery_alertOpenFiles_bytecode"

examples/Hello.re, examples/dune, package.json, src/Native/dialog.c
This PR is a really simple fix to get bytecode builds working (updates `examples/dune` to provide the proper ocamlc flags & allow building bytecode) and then 2 simple `esy` scripts to get build bytecode/native executables work.
=> Enable bytecode builds

src/Core/App.re, src/Core/App.rei
From a conversation with @glennsl today - we should allow a `force` quit (which ignores any `canQuit` callbacks registered with the window).
We assume that, if a developer is calling `App.quit`, then they probably mean to force quit - so `force` defaults to true. However, if `force` is `false`, we'll still run the `canQuit` callbacks.
=> API: App - add '~askNicely' argument to App.quit

.ci/format.sh, package.json
@glennsl pointed out that `-E` is not a universal expression for GNU `find`.
Annoyingly macOS uses BSD `find` which has slightly different configuration flags than GNU's.
@glennsl, can you checkout this branch to see if it works for you? I have tested it on:
- macOS
- Windows
- Ubuntu 19.10
- Bodhi Linux
But I don't want to merge this unless it really does fix the issue, obviously
=> Fix formatting bugs on Linux and Windows

src/Native/cocoa/ReveryAppDelegate.c
Fix https://github.com/revery-ui/revery/issues/703. (Well will once actually moved to a sensible place).
Where does it make sense to add this? I'd guess a new function that we let users call to disable it. The one potential complication is that it only needs setting one time. Once its set, you get it set permanently. So we'd probably need a disable option too.
(For anyone testing this, you can follow up with a `defaults delete com.revery.examples` in bash to remove the key it adds for now, to test before and after.)
I've confirmed the fix works over in Oni2 as well.
=> [WIP] Fix key-repeat.

examples/Examples.re, examples/NestedClickable.re, src/UI/Mouse.re, src/UI/UiEvents.re, src/UI_Components/Button.rei, src/UI_Components/Clickable.re, src/UI_Components/Clickable.rei, test/UI/MouseTest.re
Addresses #709
This allows clickables to be nested without ancestors hijacking the clicks of its descendants. It does so by implementing a local capture mechanism instead of using the global one that can be hijacked by anything anywhere in the codebase. By combining a module-local and component-local flag we can at least ensure that nothing outside the module can interfere, and we prevent different instances of the component from stepping on each others toes. The first instance to capture, which will be the deepest node, keeps the "lock" until it releases it, on `mouseleave`, `mouseup` or unmount. Hopefully that covers all the bases, but if not it's at least easier to reason about the mutation when it's local and encapsulated.
This also simplifies and fixes the `BubbleEvent` …
=> Fix nested clickables

.gitattributes
This change enables syntax highlighting correctly and may improve readability on the GitHub.
=> Recognize all re files as Reason

src/Core/App.re, src/Native/Revery_Native.c, src/Native/notification.c
Revert pieces of https://github.com/revery-ui/revery/pull/672 to work around #713 so we can upgrade to latest Revery for Onivim 2.
=> Partially revert #672 to work around #713

src/Native/Revery_Native.c, src/Native/cocoa/ReveryAppDelegate.c, src/Native/cocoa/ReveryAppDelegate.h, src/Native/cocoa/SDLAppDelegate.h, src/Native/notification.c
This fixes #713 by adding an `sdlDelegate` attribute to `ReveryAppDelegate` and calling it's `applicationDidLaunch` method (among others) when `ReveryAppDelegate`'s is called.
@bryphe @CrossR this works on my machine, but please verify it on yours! I don't want the same mistake to happen again.
My apologies that this is necessary in the first place.
=> [macOS] Fix #713

bench.esy.lock/index.json, doc.esy.lock/index.json, esy.lock/index.json, js.esy.lock/index.json, package.json, test.esy.lock/index.json
This supercedes at least parts of #723 
In addition to using native printf to avoid crashing on Windows, this:
- appends to the log file, so multiple processes can safely log to the same file. An optional `truncate` argument can be passed to `setLogFile`, which the main process can use to start from scratch each time.
- timestamp added to the log file header
- uses black foreground for all log levels, since that seems to be most legible with normal terminal colors
=> Dependency: timber -> ae5de6c

examples/Examples.re, src/Core/App.re, src/Core/App.rei
This adds a `Revery.App.initConsole` API, which, on Windows, does the following:
- If there is a console available in a parent process, it will attach to that console (ie, running the example app from the command line)
- If there is no console available in the parent process, it will allocate a new console (which creates a console session in a new window).
In the case where we do not log out, no console window will be created, which speeds up startup time.
=> API: Add a helper API to allocate a console on Windows

src/UI_Components/Slider.re
This fixes the slider so that it tracks the mouse at the center of the thumb, rather than at the leading edge.
It would be more correct to have it adjust for the mouse position relative to the thumb on mouse down and have it track the mouse so it stays in the same position rather than "jump" to position the mouse in the center of it, but that would require a significant refactor so this will have to do for now. This is still pretty decent behaviour when clicking outside the thumb, on the track, and mimics vscode's behaviour in that case.
=> Fix slider mouse tracking

bench.esy.lock/index.json, doc.esy.lock/index.json, esy.lock/index.json, examples/Examples.re, js.esy.lock/index.json, package.json, src/Core/Log.re, src/Core/Log.rei, src/Core/Performance.re, src/Core/Window.re, src/UI/Focus.re, src/UI/Mouse.re, src/UI/Node.re, src/UI/Render.re, src/UI/Ui.re, src/UI_Components/Clickable.re, test.esy.lock/index.json
Adds a trace level for the more intense log messages. amongst a few other things. The default log level in the example is `perf`, which is in between `debug` and `trace`. If `trace` logging is needed it needs to be enabled manually.
Also note that the timber API has changed significantly, so this needs to be merged along with the corresponding Oni2 PR.
=>  Dependency: timber -> ae065bb 

examples/BenchmarkExample.re, examples/Examples.re, src/Core/Window.re, src/Core/Window.rei
This adds some benchmarks for basic drawing primitives (`drawString`, `drawRect`), so we can compare the performance before/after integrating Skia.
Current results on my Mac Mini:
`master`:
| `drawString` | `drawRect` | `drawString`+`drawRect` |
| --- | --- | --- |
| ~9.152s | ~0.428s | ~9.58s |
`skia` (unoptimized - can be further improved by caching `Paint.t` objects)
| `drawString` | `drawRect` | `drawString`+`drawRect` |
| --- | --- | --- |
| ~2.3s | ~0.289s | ~2.65s |
=> Example: Add benchmarks

examples/Examples.re, src/UI/Revery_UI.re, src/UI_Components/ClipContainer.rei, src/UI_Components/Container.rei, src/UI_Components/Positioned.rei, src/UI_Components/Ticker.rei
`element` is useful as a short-hand when you add interfaces to modules that export components.
`renderFunction` is what `Ui.start` returns, but the type wasn't exposed, so couldn't actually be referenced..
=> add UI.element and UI.renderFunction type aliases

src/UI/Node.re, src/UI/Transform.re
A hot path for Revery performance, besides the core rendering, is the `recalculation` step:
https://github.com/revery-ui/revery/blob/395ed2ed531ddc9c8632cb299067e6ce8b87cf43/src/UI/Node.re#L241
This is where we compute various aspects of the `node`, in preparation for rendering and hit testing:
- `transform`
- `worldTransform`
- `boundingBox`
- `boundingBoxClipped`
These tend to be expensive (because matrix multiplication is expensive), and allocations are also expensive when they happen a lot - reducing allocations is keep to keeping garbage collection at bay!
One inefficiency that was occurring in this phase is that, when we were computing the animation transforms - the `style=Style.[transforms(....)]` property - we were always allocating a matrix and doing a multiply, but most of the …
=> Perf: Skip matrix allocation + multiply (preConcat) if no transforms

bench.esy.lock/index.json, bench.esy.lock/opam/zed.2.0.5/opam, doc.esy.lock/index.json, doc.esy.lock/opam/zed.2.0.5/opam, esy.lock/index.json, esy.lock/opam/zed.2.0.5/opam, examples/BenchmarkExample.re, js.esy.lock/index.json, js.esy.lock/opam/zed.2.0.5/opam, package.json, src/Draw/CanvasContext.re, src/UI/TextNode.re, test.esy.lock/index.json, test.esy.lock/opam/zed.2.0.5/opam
- Pick up the `Canvas.drawRectLtwh` API, which avoids a rect allocation in the simple case of drawing a rectangle.
- Pick up `Paint.setSubpixelText`
=> Dependency: reason-skia -> 3cc83e0, use new methods

examples/BenchmarkExample.re, src/Draw/CanvasContext.re
So that the `Ltwh` match up with `left`, `top`, `width`, `height`
=> API: DrawRectLtwh - use left and top for params

src/Font/FontRenderer.re
On Windows, in Onivim 2, the text was not being spaced and measured correctly.
When measuring a character with the `FiraCode-Regular.ttf` font - on OSX, it would correctly report a width of `8.4`. On Windows, though, it would report a width of `8.0`, which is incorrect, and resulted in the text on the editor surface being 'squished.
Very obviously bad if you look at the semicolons:
The difference is actually in the parameters we were providing the `Paint` we use to measure the text. On OSX, subpixel text was defaulted to true, but on Windows it wasn't. When we render, we set it, but we weren't setting it when measuring - and this caused the measurement to be slightly off.
The fix for now is to synchronize the settings we use in measure and in drawing. 
If we decide to make subpixel or LCD …
=> Bugfix: Text.measure - Use consistent settings with text & measure

src/Font/FontRenderer.re, src/UI/TextNode.re
Skia supports subpixel character position rendering via `setSubpixelText`, but this can affect measurement and metrics.
On some platforms, subpixel rendering isn't supported - so this can skew our measurements when the rendered text doesn't align with the measurements we expect. For now, I'll turn it off, until we can reliably detect when it will be enabled, or have a configuration story for it.
Note that this doesn't disable anti-aliasing, or lcd striping - just subpixel positioning.
=> Skia: Disable subpixel text until configurable

bench.esy.lock/index.json, doc.esy.lock/index.json, esy.lock/index.json, js.esy.lock/index.json, js.esy.lock/opam/lambda-term.2.0.3/opam, package.json, src/Draw/CanvasContext.re, test.esy.lock/index.json
On Wayland, with the Skia integration, we are seeing a blue (empty) screen on rendering:
https://github.com/onivim/oni2/issues/1283
The root cause is that the default Skia Gl interface, on Linux, defined here: https://github.com/revery-ui/esy-skia/blob/master/src/gpu/gl/glx/GrGLMakeNativeInterface_glx.cpp
uses X11 APIs, like `glXGetProcAddress` to get the OpenGL API surface. On Wayland, though, that API won't work.
Instead, we pick up a change in `reason-skia` (https://github.com/revery-ui/reason-skia/pull/3) to use the `SDL_GL_GetProcAddress` method to supply the GL interface.
=> Fix Skia rendering on Wayland

src/UI/TextNode.re, src/UI/ViewNode.re
Cache `Skia.Paint` objects for TextNode and ViewNode to reduce allocations on the hot render path.
=> Perf: Cache paint objects for ViewNode/TextNode

bench/lib/ViewNodeBench.re, src/Draw/CanvasContext.re, src/UI/ViewNode.re
This improves the `viewNode#draw` performance by pre-allocating some Skia objects, and adds a benchmark to track.
__Previous performance:__
```
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  BENCHMARK                                                     |  ITERATIONS |  TIME               |  MINOR GC  |  MAJOR GC  |  MINOR ALLOC  |  PROMOTED  |  MAJOR ALLOC  |
|----------------------------------------------------------------+-------------+---------------------+------------+------------+---------------+------------+---------------|
|  ViewNode: draw single node                                    |  10000      |  0.0239310264587    |  8         |  1         | …
```
=> Perf: Improve ViewNode draw performance

esy.lock/index.json, esy.lock/opam/ppx_tools.5.3+4.08.0/opam, package.json
Trying to figure out what breaks the macOS CI in https://github.com/onivim/oni2/pull/801. Let's see if revery CI succeeds with 4.08.
=> Dependency: ocaml -> 4.08

bench.esy.lock/index.json, bench/lib/PaintBench.re, doc.esy.lock/index.json, esy.lock/index.json, examples/CanvasExample.re, js.esy.lock/index.json, package.json, src/Core/Color.re, src/Core/Color.rei, src/Core/Window.re, src/Draw/DebugDraw.re, src/UI/ViewNode.re, test.esy.lock/index.json, test/Core/ColorTests.re
This picks up performance improvements in https://github.com/revery-ui/reason-skia/pull/48 , so that the hot-path of setting the paint color is as fast and streamlined as it can be.
This adds a benchmark for setting paint colors:
```
|----------------------------------------------------------------+-------------+---------------------+------------+------------+---------------+------------+---------------|
|  Paint: Set color                                              |  10000      |  0.000262975692749  |  0         |  0         |  30027        |  0         |  0            |
|----------------------------------------------------------------+-------------+---------------------+------------+------------+---------------+------------+---------------|
```
And brings in several fixes, including …
=> Perf: Benchmark and improve setting Color

bench.esy.lock/index.json, doc.esy.lock/index.json, esy.lock/index.json, js.esy.lock/index.json, package.json, src/Draw/CanvasContext.re, test.esy.lock/index.json
...and fallback to `makeSdl2` only if that fails
Picks up https://github.com/revery-ui/reason-skia/pull/51
Hopefully fixes #759
=> Fix #759: Use Skia.Gr.Gl.Interface.makeNative by default

examples/Examples.re, src/Core/Window.re
__Issue:__ When `titlebarStyle` is set to `Transparent`, after minimize + restore (or maximize + restore), the titlebar is visible again.
__Fix:__ Reset the titlebar style on window restore.
=> Bugfix - OSX: Fix titlebar style on restore

src/UI_Hooks/Spring.re
This change adds an `enabled` property to the spring.
In addition, I noticed a bug with the `restThreshold` - once the rest threshold has been reached, there would be no further animation. This is OK for low values of `restThreshold`, where the spring would've been close to its final destination, but for higher values, the spring may stop animating far away from the destination. This clamps the spring in the case there is no animation (ie, if it is resting, or not active).
=> Spring: Add enabled property to spring; fix bug with rest

src/Core/Tick.re, src/UI_Hooks/Timer.re, test/UI/HooksTest.re, test/UI/dune
While experimenting with a cursor animation in `revery-terminal` (https://github.com/revery-ui/revery-terminal/pull/1) - I saw there was a pretty bad bug... Sometimes the spring hook would never settle into a rest state, and continually redraw - even when the animation was completed. This was pretty easy to repro - all it would take is running a `git status` or type commands quickly, but it was intermittent.
I did some logging in the spring hook here: https://github.com/revery-ui/revery/blob/a525e7f07d1417791c6ac2b574ed7fb9e68ceaeb/src/UI_Hooks/Spring.re#L14
And saw that `isActive` was being set to `false` for both springs (the x & y springs), and the `Timer.timer` hook was getting `isActive` of `false`... but one of the timers was still ticking. So it seems like the root issue is in the …
=> Bugfix: Ensure timer is always disposed

bench.esy.lock/index.json, doc.esy.lock/index.json, esy.lock/index.json, js.esy.lock/index.json, src/Draw/Text.re, src/Font/FontRenderer.re, src/Font/Revery_Font.re, src/Font/Smoothing.re, src/UI/TextNode.re, src/UI_Components/Input.re, src/UI_Primitives/Text.re, test.esy.lock/index.json
This is the revery-side fix for: https://github.com/onivim/oni2/issues/1364
The measurement / metrics of character width are impacted by the font smoothing settings (specifically, whether subpixel text is allowed). 
Because this is an important consideration for measurements, we should make our measurement APIs take a required argument for this - to ensure the caller has considered the smoothing type.
=> API - Font Measurements: Make smoothing type explicitly required

bench.esy.lock/index.json, doc.esy.lock/index.json, esy.lock/index.json, js.esy.lock/index.json, package.json, test.esy.lock/index.json
Finally got timber published. Tried to publish it to opam first, since I think that's where it belongs and since there's already an npm package of the same name, but I'm unable to authenticate with GitHub using 2FA for some unknown reason, so npm it is! It's now published as `@glennsl/timber`.
=> Dependency: timber -> 1.0.0

bench.esy.lock/index.json, doc.esy.lock/index.json, esy.lock/index.json, js.esy.lock/index.json, package.json, test.esy.lock/index.json
- Pick up memory leak fix in reason-font-manager: https://github.com/revery-ui/reason-font-manager
=> Dependency: reason-font-manager -> 2.0.2

examples/Slider.re, src/UI/Node.re, src/UI/NodeEvents.re, src/UI_Components/Slider.re, src/UI_Primitives/Canvas.re, src/UI_Primitives/View.re
While adding the scrollbar / scrollback to [`revery-terminal`](https://github.com/revery-ui/revery-terminal/pull/13) - I noticed a bug with the slider (which we're using as a scrollbar).
In some cases - when using it in a 'controlled' manner, it would pick up stale values. There were two contributing factors:
- The `ref` + query for bounding box strategy could sometimes be out of date. The fix for this was to have an explicit event to listen to bounding box changes.
- The 'controlled' scenario relied on calling a `setState` handler, but this wasn't reliable - we'd still get stale values back. Instead, I made a slight API change - for uncontrolled components, `initialValue` is enough to set, and isn't monitored. For controlled components - the `value` property should be used.
__TODO:__
=> API: OnBoundingBoxChanged + Slider fixes

azure-pipelines.yml, bench.esy.lock/index.json, bench.esy.lock/opam/fix.20200131/opam, bench.esy.lock/opam/ppx_tools_versioned.5.3.0/opam, bench.esy.lock/overrides/opam__s__menhir_opam__c__20200211_opam_override/package.json, doc.esy.lock/index.json, doc.esy.lock/opam/fix.20200131/opam, doc.esy.lock/opam/ppx_tools_versioned.5.3.0/opam, doc.esy.lock/overrides/opam__s__menhir_opam__c__20200211_opam_override/package.json, esy.lock/index.json, esy.lock/opam/fix.20200131/opam, esy.lock/opam/ppx_tools_versioned.5.3.0/opam, esy.lock/overrides/opam__s__menhir_opam__c__20200211_opam_override/package.json, js.esy.lock/index.json, js.esy.lock/opam/fix.20200131/opam, js.esy.lock/opam/ppx_tools_versioned.5.3.0/opam, js.esy.lock/overrides/opam__s__menhir_opam__c__20200211_opam_override/package.json, src/Core/Environment.re, test.esy.lock/index.json, test.esy.lock/opam/fix.20200131/opam, test.esy.lock/opam/ppx_tools_versioned.5.3.0/opam, test.esy.lock/overrides/opam__s__menhir_opam__c__20200211_opam_override/package.json
We use `Revery.Environment.executingDirectory` in a way that we assume is always an absolute path. 
However, it looks like there could be cases on Linux where this wasn't the case - this checks if the path is absolute, and if it isn't, applies the current working directory to get a fully absolute path.
=> Bugfix - Environment: Ensure executingDirectory is absolute

.github/workflows/validate-pr.yml, doc.json, src/Revery.re
Ok so now lockdir update should be more resilient to package.json non-valid.
the issue before we removed all the lockdir to ensure we have a clean lockdir and we could detect newer dependencies that will break our build. So if a commit without a lockdir is pushed the CI was out. I have opted for a soft `esy install` I will bring the old behaviour back with the new @revery-bot after.
=> Fix lockdir update, and reporter

src/Font/Smoothing.re
__Issue:__ There were several issues reported with Onivim, where the text / cursor wouldn't match up, ie:
https://github.com/onivim/oni2/issues/1475
https://github.com/onivim/oni2/issues/1592
(And I know @CrossR has to help lots of people troubleshoot / tell them to switch their font settings to `subpixel-antialiased`).
__Defect:__ From my investigation - it seems that in the case of a scaled display (ie, using `--force-device-scale-factor`, or an inferred scale, like `GDK_SCALE`) could cause the text metrics to be calculated incorrectly (at least, out of sync with how they are rendered).
The main issue is that text sizes may scale non-linearly - so, if a font has a measured width of `7.5px` at `14px` line height, there's no guarantee that the same font at a `28px` line height will have a …
=> Bugfix - Font Smoothing: Use subpixel text as default

src/UI_Components/Clickable.re, src/UI_Components/Clickable.rei
Fix #817 by adding an `onDoubleClick` callback and `doubleClickDelay` value to `Clickable`.
Hopefully, this is a reasonable way of doing this.
=> Implement #817 - Add onDoubleClick to Clickable

bench.esy.lock/index.json, doc.esy.lock/index.json, esy.lock/index.json, js.esy.lock/index.json, package.json, test.esy.lock/index.json
The `esy-cmake` resolution is no longer needed.... we can be free of resolutions, which will make it simpler to add `revery` as an `esy` dependency.
=> Dependency: Remove cmake resolution

examples/InputExample.re, src/UI_Components/Input.re
This adds a boolean option to the input component to obscure the entered value on render:
The name `typePassword` is based on the [input type of html element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password). I can change it if something like `obscureValue` makes more sense.
=> add password type inputs

src/Core/Window.re
As discussed in #840 (and merges into that, of course)
This does everything I suggested, except replacing the dirty flag with a variant to prevent invalid data from being accessed, as that would be pretty invasive. All this currently does is move code around to make the contract explicit.
=> refcactor: encapsulate WindowMetrics better

.ci/esy-check-hygiene.yml, src/Core/Window.re, src/Core/Window.rei, src/Core/WindowCreateOptions.re, src/UI/Render.re
Motivated by https://github.com/onivim/oni2/pull/1752 - this addresses an inconsistency in the Revery `Window` API in talking about sizes - there are two window sizes that SDL gives us - the 'screen space' size, and the 'framebuffer' size. On top of that, we also account for display scaling (like frameworks like Electron handle). So that makes three 'spaces' for window sizes:
1) Screen space size
2) Screen space size, _scaled based on display settings_
3) Framebuffer pixel size (the size of the 'backbuffer' that we render to - this is in pixels can vary depending on the device pixel ratio of the screen. For example, retina displays would be some multiple of the screen space size).
For the purposes of window management, we only care about 1 & 2 - framebuffer size is important for rendering …
=> refactor(window): Update Window API to differentiate between scaled/unscaled sizes

test/TestRunner.re
__Issue:__ `esy @test run` stopped producing output on all the windows devices I tried.
__Defect:__ Linking in `reason-sdl2` brings in the `-mwindows` flag, which causes the application to not allocate or attach console.
__Fix:__ Explicitly attach a console for the test runner.
Fixes #843  - I guess we both hit this at the same time, @Et7f3 !
=> fix(test/#843): Fix windows output for test cases

examples/Examples.re, examples/HitTests.re, src/Core/Window.re, src/Core/Window.rei, src/Core/WindowCreateOptions.re, src/UI/HitTest.re, src/UI/Node.re, src/UI/Ui.re, src/UI/Ui.rei, src/UI_Primitives/Text.re, src/UI_Primitives/View.re
This adds an attribute to all nodes that changes their mouse
behavior based on SDL2's hit test results.
i.e.
```reason
<View
mouseBehavior=Draggable
...
/>
```
GIF:
I want to make sure this works cross-platform before I merge it in. I've tested in on macOS and can test on Linux. @bryphe would you be able to test on Windows? That would be super helpful 😃.
From what I can tell the `Resize` types don't work on macOS. I don't think this is evidence of something wrong either here or in `reason-sdl2`. I'll do some research to see if they're supposed to work.
=> feat(window): bind Node mouseBehavior to SDL hit-tests

examples/Examples.re, examples/WindowControl.re, src/Core/Window.re, src/Core/Window.rei
This is necessary for Onivim2's custom titlebar on Windows.
I added a quick little example to show it working:
Everything works as it should on macOS at least. Since I'm only using SDL2's built-in methods I think it's safe to assume that means it works everywhere.
=> feat(window): add restore function

src/UI_Components/Input.re
Perhaps there is a reason why `scrollOffset` was using `Hooks.state(ref(0))`, but as far as I could tell, it was unnecessary. I switched it to `Hooks.ref(0)`
=> Switch scrollOffset to Hooks.ref

src/UI/HitTest.re, src/UI/Ui.re
This totally flew under the radar because I'm on a Mac and (I assume) @bryphe and I have our scaling set to 1.0 on Windows, but I didn't scale the mouse coordinates properly on the HitTest params and FileDrop events.
@CrossR noticed this in onivim/oni2#1801, and I think this fixes that.
@CrossR, if you could resolve Revery in your local Oni `package.json` to the latest commit here and see if that fixes the issue, that would be super helpful!
Sorry this was overlooked in the first place! Luckily it doesnt seem to be _too_ hard a fix!
=> fix(events): fix mouse positions not scaling correctly

src/Core/App.re, src/Core/Window.re, src/Native/Initialization.re, src/Native/Revery_Native.c
People in the Oni Discord were noting that an undecorated Window was covering the taskbar on Windows. Luckily, I found that Chrome had that same problem: https://chromium.googlesource.com/chromium/src.git/+/46.0.2478.0/chrome/browser/ui/views/apps/chrome_native_app_window_views_win.cc#71
This fixes that by adding an `Revery_Native.initWindow` function that sets the flag after all the SDL modifications are done. 
This also renames `Revery_Native`'s `init` to `initApp` to avoid confusion.
=> fix(Windows): ensure WS_CAPTION is set on undecorated windows

src/UI/Focus.re, src/UI/Focus.rei, src/UI/Keyboard.re, src/UI/Mouse.re, src/UI_Components/Input.re
I renamed `dispatch` to `focus` and `focus` to `focusWithoutBlur`.
(I accidentally screwed up the other pull request.)
I ran `esy format` and it didn't change anything, but hopefully it's happy now. I also am not sure what the unused variable mentioned is.
=> Stop separately tracking focus for Input

examples/Examples.re
To make it easier to test cases like #869 - this adds a `--force-device-scale-factor` option, like: 
```
esy run --force-device-scale-factor=1.5
```
so that the example app can be run scaled.
=> feat(example): Add --force-device-scale-factor option to make it easier to test

azure-pipelines.yml
This sets up triggers to auto-cancel PR builds when a new commit has been pushed
=> chore(ci): Fix up triggers to reduce backlogs of builds in azure pipeline queue

.github/workflows/validate-pr.yml, scripts/docker/archlinux/Dockerfile, scripts/docker/centos/Dockerfile
Windows is added so we know we don't break major OS.
Centos is added to have parity with azure pipeline.
ArchLinux is added because it is a rolling release.
This PR also fix push docs from other non-master.
This PR also cache store from docker :) We can't see it because it isn't merged.
You can check it build here: https://github.com/revery-ui/revery/runs/732801762?check_suite_focus=true because without cache it is too much slow.
With this the build matrix get high. If we plan on adding build for IOS we might get another build: so we have to decide strategy ? Does it is fine that we wait a bit. Today we have 3 active PR so I have to kill some CI run. I haven't really this before so what do you think ?
=> Add windows, centos, archlinux in GHA CI

examples/CanvasExample.re, src/Draw/CanvasContext.re
This adds `CanvasContext.concat`, enabling transforms to be applied in the canvas rendering function without overriding any other transform that might have been applied.
=> feat(canvas): add concat (matrix)

src/Font/FontFamily.re
This is a temporary fix to address #894. On macOS, Arial is bundled as separate files so this is a good font to use until #894 is fixed.
=> fix(macOS/fonts): change default macOS font to Arial

bench.esy.lock/index.json, doc.esy.lock/index.json, esy.lock/index.json, examples.esy.lock/index.json, js.esy.lock/index.json, package.json, test.esy.lock/index.json
Apparently `esy` isn't able to unify the full hash and short hash of dependencies, and since it's a pain in the ass to reproduce the full hash in every package that needs it, I opted for just shortening this instead.
=> shorten reason-native-crash-utils commit hash

src/UI/Keyboard.re
This introduced an accidental change converting KeyDown events into KeyUp events. That lead to Inputs not calling their `onKeyDown` handler anymore.
https://github.com/revery-ui/revery/commit/e5f363a1ac1d2b3a91f30ce936efa18478fedb1a#diff-dca70cf54f7954dcef8dd3e027ccb53eR21
This fixes it.
=> fix accidentally converting keydown to keyup

src/Core/Window.re
=> fix(rendering/#878): use 1.0 as default scale factor for Linux

.gitignore, examples/skia-font-manager-cli/SkiaFontManagerCli.re, src/reason-skia/Skia.re, src/reason-skia/Skia.rei, src/reason-skia/wrapped/bindings/SkiaWrappedBindings.re, src/reason-skia/wrapped/lib/raw_bindings.c, src/reason-skia/wrapped/stubgen/stubgen.ml, src/reason-skia/wrapped/types/SkiaWrappedTypes.re
This does a couple main things:
- Creates a `Stream` module
- has `getLength` & `hasLength` functions
- Adds a `Data.ofStream` function (`sk_data_new_from_stream`)
- Adds a `Typeface.openStream` function (`sk_typeface_open_stream`)
- Writes the found Arial typeface to a file, `Arial.ttf` in the `SkiaFontManagerCli` example
This adds a small C error that Im not sure if there's a mechanism to fix within ctypes. The stream returned by `sk_typeface_open_stream` is an `sk_stream_asset_t` ([`SkStreamAsset`](https://api.skia.org/classSkStreamAsset.html)), which, in the C++/OOP world, is a subclass of `sk_stream_t` ([`SkStream`](https://api.skia.org/classSkStream.html)). However, since there's no notion of inheritance in C the compiler gives an incompatible pointer types warning. We have other …
=> feat(reason-skia): bind to `sk_typeface_open_stream` and `sk_stream_t`

examples/skia-font-manager-cli/SkiaFontManagerCli.re, src/reason-skia/Skia.re, src/reason-skia/Skia.rei, src/reason-skia/wrapped/bindings/SkiaWrappedBindings.re, src/reason-skia/wrapped/types/SkiaWrappedTypes.re
This is a really small change that just adds two functions from `FontMetrics`: the average character width and the maximum character width. These functions make it easy to test if a loaded font is monospace through
```
FontMetrics.avgCharacterWidth(metrics) == FontMetrics.maxCharacaterWidth(metrics)
```
I tested this with Consolas and it worked. Fortunately it also worked with FiraCode (I was worried that maybe the ligatures would register strangely).
=> feat(reason-skia): bind to `FontMetrics` char width functions

src/Font/FontMetrics.re, src/UI/TextNode.re, src/UI_Components/ClickableText.re, src/UI_Components/Link.re, src/UI_Components/Markdown.re, src/UI_Primitives/Text.re
This is another fairly simple addition. We get the underline info from Skia via FontMetrics and draw a rectangle from it.
Here's what the text looks like all underlined (before I added the property):
I also added it to the components that use `Text`, like `ClickableText` and `Link`. I made `Link`s underlined by default and `ClickableText`s not.
=> feat(components): add `underline` prop to Text component

src/UI_Components/Markdown.re, src/UI_Components/Markdown.rei
When I was originally testing this it was picking up my system monospaced fonts so I didnt notice the font props were incorrect. However any path based font is going to be incorrect.
My bad 🤦‍♂️.
=> fix(markdown): Fix wrong font families in code blocks

src/UI_Components/Markdown.re, src/UI_Components/Markdown.rei
I originally had this as `codeBlockColor`, but when implementing the hover in Oni I realized it makes sense to have more granular control over the code block.
=> refactor(Markdown): change `codeBlockColor` prop to `codeBlockStyle`

examples/MarkdownExample.re, src/UI/TextNode.re
Previously we were casting the float returned from the text wrap call directly to an int. This was causing remeasures to improperly wrap because we shaved off the fractional space required for the text.
=> fix(render): fix text getting cut off from improper int <-> float conversion

src/UI_Components/Markdown.re, src/UI_Components/Markdown.rei
This is to help fix text appearing to small in code blocks, as noted in onivim/oni2#1947.
=> fix(Markdown): add code block font size parameter

src/reason-sdl2/sdl2.re
OCaml on 32bits systems, have an int size of 31 bits, but SDL keycodes are actually 32bits integers, and some of them actually uses 31 bits of the integer, like `let right = 1073741903`.
One platform that suffers of this is problem is the Raspberry Pi, which by default is 32bits.
There is no SDL keycode negative, so to fix that without a breaking change we can use the negative part of our 31 bits int to fit any SDL keycode.
The only problem is that if you try to serialize big keycodes they will be different based on the platform, that is not ideal, but seems like a really small edge case and changing everything to `int32` is probably not worth it.
=> sdl2 escapes keycodes to support 32bits

examples.json, examples/dune, package.json
This moves the examples from the Revery package to the ReveryExamples package.
This has two advantages:
- Revery no longer builds the examples as part of the library. It doesn't really make sense for a consumer to build all the examples when they wont use them. Unless I'm missing something, this seems like a positive.
- The examples can use the Revery library as an external consumer. This will help to get separate bytecode and native builds working for the examples.
=> refactor(examples): move examples to ReveryExamples package

src/reason-sdl2/sdl2_wrapper.cpp
Related: https://github.com/onivim/oni2/issues/2003
Revery apps, and Onivim 2, disable KDE compositing. This is because SDL disables compositing by default - this default makes sense for games that run full-screen. For a tool, or a windowed app like Revery / Onivim 2, it's problematic and unexpected to disable compositing.
This sets the `SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR` to `0` so that we disable this behavior.
=> fix(linux): Disable X11 compositor suppression (enable compositing)

examples/Examples.re, examples/FontsExample.re, src/Font/Discovery.re, src/Font/FontFamily.re, src/Font/Revery_Font.re
After #918 instead of the applications crashing when a font is not found it throws a `Font_not_found` , but there is some platforms like Android who will never have a font because it's using a `dummy` font-manager, so we need a way to handle that.
This is not a great API, but shouldn't be a problem considering that this kinda of choice should be handled on an application level. We can mark it as unstable or deprecated.
Still proposed it, because it's a nice to have even if it's not great and we can use it to develop a proper implementation to replace it later.
=> feat(font-manager): fallback when Font is not found

src/UI_Components/Input.re
This fixes `Input` allowing it to work correctly when all the new font stuff is set.
This was causing other bugs as well because the cursor positioning was done based on the actual font while the text being displayed was using a different font.
=> Pass font info to input text

src/reason-harfbuzz/harfbuzz.cpp
@bryphe caught that we were incorrectly calculating the length of the returned buffer. I fixed the call order and the glyph_count.
The string "fi" now correctly only returns one glyph in Roboto Mono, and the other strings work as they did before.
=> fix(harfbuzz/#933): Invalid glyph counts w/ Ligatures

bench.json, doc.json, examples.json, package.json, sdl2.opam, src/reason-sdl2/config/discover.re, src/reason-sdl2/dune, src/reason-sdl2/sdl2_wrapper.cpp, test.json
By removing the use of `uname` we can cross compile from Linux to Mac / Window and from Mac to Linux / Windows. It's a neat tooling for development as compiling from a powerful Linux computer is a lot faster than compiling on Windows(especially for me).
Also used the `SDL_config.h` to detect features available, this should also fix **wayland** and it's half of the problem regarding iOS and Android.
Feature detection for this specific case is quite hard, I plan to have it, but in the futuru, also there is some options with are inherently system based. So this is a middle ground for now but may change in the future.
=> sdl2 better feature and system detection

src/Native/Revery_Native.c, src/Native/cocoa/ReveryAppDelegate.c, src/Native/cocoa/ReveryAppDelegate.h, src/Native/cocoa/ReveryAppDelegate_func.c, src/Native/cocoa/ReveryAppDelegate_func.h, src/Native/cocoa/ReveryProgressBar.c, src/Native/cocoa/SDLAppDelegate.h, src/Native/config/discover.re, src/Native/dialog.c, src/Native/dialog_cocoa.c, src/Native/dialog_gtk.c, src/Native/dialog_win32.c, src/Native/dune, src/Native/icon.c, src/Native/icon_cocoa.c, src/Native/icon_win32.c, src/Native/locale.c, src/Native/locale_cocoa.c, src/Native/notification.c, src/Native/notification_cocoa.c, src/Native/shell.c, src/Native/shell_cocoa.c, src/Native/shell_gtk.c, src/Native/shell_win32.c
We currently use `__APPLE__` and `__linux__` to detect if the system uses Cocoa or GTK, that's a problem on iOS and Android as they don't have Cocoa and GTK
Using a config header generated at `discover.re` makes it more portable, so when adding a new platform only the platform dependent code of this specific new platform, will need to change.
Another alternative would be to use `-D` on the command line, but that is harder to replicate and the editor integration is worse.
This is the last platform independent change to get Android and iOS on Revery. The next ones should be Android and iOS respectively.
=> More feature detection

bench.json, doc.json, examples.json, package.json, src/Core/Environment.re, src/Core/Environment.rei, src/Core/Window.re, src/Native/Environment.re, src/Native/Revery_Native.re, src/Native/config/discover.re, src/Native/dialog.c, src/Native/dune, src/Native/environment.c, src/Native/locale.c, src/Native/shell.c, src/reason-sdl2/config/discover.re, src/reason-skia/config/discover.re, test.json
There is quite some duplicated code happening, related to system detection, probably in the near future I would like to change how we do that.
- Get the OS during runtime using the value from `config.h`
- Add Android specific flags to reason-sdl2 and reason-skia
- Add special handle for Android scale factor
Currently esy doesn't provide the needed tools, so we need some hacks, they're provided at [reason-mobile](https://github.com/EduardoRFS/reason-mobile)
=> feat: Android

src/Core/App.re, src/Core/Environment.re, src/Core/Environment.rei, src/Core/Window.re, src/Draw/CanvasContext.re, src/Native/Environment.re, src/Native/config/discover.re, src/Native/locale.c, src/reason-sdl2/config/discover.re, src/reason-sdl2/sdl2.re, src/reason-sdl2/sdl2_wrapper.cpp, src/reason-skia/config/discover.re
Again, more system detection code, but this time is done.
- Add iOS specific flags to revery, reason-sdl2 and reason-skia
- proper detection of framebufferId
- the application lives inside an SDL_main
This last change is required as our application needs to live inside the [UIApplicationMain](https://github.com/SDL-mirror/SDL/blob/2cf2cfd5b0b0e634bba32295d7ba7e64b298aea3/src/video/uikit/SDL_uikitappdelegate.m#L70), this is essentially a no-op on other platforms.
Same as #943 will publish a guide and a CI today
=> feat(native): support iOS

examples/text-wrap-cli/ReveryTextWrapCli.re, src/Core/TextWrapping.re, src/Draw/Text.re, src/Draw/Text.rei, src/Draw/dune, src/UI/TextNode.re, src/revery-text-wrap/wrap.re, src/zed/zed_utf8.ml
Now that we have @OhadRau's revery-text-wrap in the monorepo, we need to make it UTF-8/Unicode aware so that we dont split on arbitrary byte boundaries. This was a big pain point when I was writing font-fallback, and this PR should fix it 👍
=> fix(text wrap): make UTF-8 aware

src/Font/FontCache.re
This doesn't even work properly right now, and could use some cleanup, but it shows the basic ideas I wanted to get a cross. The hole resolver has been simplified and is fully contained inside `generateShapes`, I've also tried to prepare it for using the bounded harfbuzz API. Having the bounds be bytes-based and the loop index be glyph-based is a bit confusing though. And it does need to be threaded through a lot of functions.
I'll keep working on this a bit to try to figure out why it's not working properly, and see if I can find a better way to pass the bounds around. I think it's good enough to run by you for a preliminary review though, or to show it just as an example if you want to go in a different direction.
=> reafactor(feat/font/fallback): self-contained generateShapes

packages/reason-harfbuzz/src/Harfbuzz.re, packages/reason-harfbuzz/src/Harfbuzz.rei, packages/reason-harfbuzz/src/harfbuzz.cpp, packages/reason-harfbuzz/test/FeaturesTest.re, packages/reason-harfbuzz/test/ShapingTest.re, packages/reason-harfbuzz/test/TestFramework.re
Rather than creating substrings to shape, we can just pass in the start and stop into Harfbuzz 👍
=> feat(harfbuzz): add start and stop API to shape

.ci/format.sh, packages/reason-harfbuzz/src/harfbuzz.cpp, packages/reason-sdl2/src/sdl2_wrapper.cpp
When I first added `astyle`, we didn't have any C++ files to format so I left out all `.cpp` files from formatting. Now that we have the monorepo, that's changed. I think it's a good idea to have consistent formatting across all of our native code.
=> chore(format): extend C formatting script to also format C++ files

.ci/esy-build-steps.yml, examples.json, packages/reason-skia/examples/skia-font-manager-cli/dune, packages/reason-skia/examples/skia-font-manager-cli/run-skia-fontmanager.sh, packages/reason-skia/src/Skia.re, packages/reason-skia/src/wrapped/bindings/SkiaWrappedBindings.re
Now that we have a way to suppress the fontconfig leaks, this should have leak detection. This will prevent future leaks from Skia in regards to the font manager.
=> chore(skia): bring back ASAN for SkiaFontManagerCli

src/Core/TextOverflow.re, test/Core/TextTests.re, test/Core/dune
This is a pretty simple fix, since Zed already gives us a function to do exactly what we were doing before but with UTF-8. 
I will also add some tests for this, just to make sure it's robust!
=> fix(text): make overflow UTF-8 aware

packages/reason-harfbuzz/examples/harfbuzz-cli/HarfbuzzCli.re, packages/reason-harfbuzz/examples/harfbuzz-cli/dune, packages/reason-harfbuzz/src/Harfbuzz.re, packages/reason-harfbuzz/src/Harfbuzz.rei, packages/reason-harfbuzz/src/dune, src/Font/FontCache.re
@glennsl mentioned in #927 that these two libraries should be separate, and I totally agree. This uncouples them completely, except for the examples/CI to get font discovery working. @glennsl, let me know if you want me to remove that as well.
=> fix(harfbuzz): uncouple from Skia

src/UI/Style.re
It can be hard to style with only `flexGrow`... this adds `flexBasis` and `flexShrink`, which were already partially hooked up, and completely supported by [`flex`](https://github.com/jordwalke/flex/) - so pretty easy to finish wiring up.
=> feat(style): Add flexBasis and flexShrink primitives

src/UI_Components/RichTextView.re
While creating the `FloatingNavigationBar`-example I stumbled upon the fact that I could not control the text-wrapping of a `RichTextView`. I believe this makes sense to expose, but I guess that it could perhaps be exposed on the `text`-function instead?
=> feat(components): expose text-wrap for RichTextView

packages/reason-sdl2/src/sdl2.re, packages/reason-sdl2/src/sdl2_wrapper.cpp, src/Core/Window.re, src/Core/Window.rei, src/Core/WindowCreateOptions.re, src/Core/WindowStyles.re
This adds a `transparency`-option to Window.
EDIT: I guess though, that this puts a transparency on everything, not only the "background-window" as you'd expect. 🤔 
Would close #506
=> feat(window): expose a few more window-options

src/Font/FontCache.re, test/Font/FontCacheTest.re
__Issue:__ Certain unicode constructions could cause the font-fallback algorithm to hang, as described in https://github.com/onivim/oni2/issues/2178
__Defect:__ We'd run into an infinite loop in the `fallbackFor` code, because we were assuming a `character index` when we actually needed a `byte offset`. This is another case where it'd be great to have the type system help us differentiate between these!
__Fix:__ The value passed into `fallbackFor` is a byte index, not a character index - so use `Zed_utf8.extract`, which operates on byte offsets, instead of `get`, which operates on character indices. Add several test cases.
=> fix(font): Fix hang in font-fallback code

src/Font/FontMetrics.re
This uses Skia's FontMetrics functions to get the maximum and average character widths for a given typeface.
=> feat(font): add maximum and average character widths to FontMetrics

src/Font/FontCache.re, test/Font/FontCacheTest.re
__Issue:__ When a string with a non-printable ASCII character (like `CR` - ascii 10 or `LF` - ascii code 13) was passed to be shaped, it would hit an infinite loop. 
__Defect:__ The shaping code would resolve that there was no glyph available, and then enter the fallback code path - `fallbackFor`. The problem, though, is in these cases, we'd return _the same font_ - and then we'd try and resolve the hole using the 'new' (really, the same) font - endlessly.
There also seemed to be an off-by-one issue in `resolveHole` that caused an additional glyph to be surfaced in this case.
__Fix:__ In the case where the fallback font is the same as the source font, resolving the hole isn't going to help, so detect that case and handle it the same as the error case.
__Test Impact:__
- Add cases for all …
=> fix(shaping): Hang on non-printable ASCII characters

src/Font/FontCache.re
__Issue:__ Having a font installed system-wide, and locally, could cause a hang in our font-fallback code.
__Defect:__ This is actually the same root cause as https://github.com/revery-ui/revery/pull/974 - however, there is a case exposed that we weren't handling.
This logic: 
```
| Ok(fallbackFont)
when
Skia.Typeface.getUniqueID(fallbackFont.skiaFace)
== Skia.Typeface.getUniqueID(font.skiaFace) 
```
wasn't quite sufficient. It turns out, in the case where a system font is installed that is the same as local font - we could run into a case where we have _different unique ids_ but _actually the same font_. So in this case - this equality check would be `false`, because the unique ids are different... but actually, we were getting the same font, so we'd hit the same loop as in #974 …
=> fix(font-fallback): Fix hang when font is duplicated between system / Revery

packages/reason-sdl2/src/sdl2.re, packages/reason-sdl2/src/sdl2_wrapper.cpp, src/Core/App.re, src/Core/Window.re
__Issue:__ For Onivim issues https://github.com/onivim/oni2/issues/2225 and https://github.com/onivim/oni2/issues/1185 - we still don't have enough details to get the full information. In particular, it'd be useful to see the displays attached along with their pixel formats.
__Fix:__ Add logging for each display prior to window creation to help get further in https://github.com/onivim/oni2/issues/2225 and https://github.com/onivim/oni2/issues/1185
__Test:__
=> feat(diagnostics): Additional display logging

examples/Examples.re, packages/reason-sdl2/src/sdl2.re, packages/reason-sdl2/src/sdl2_wrapper.cpp, packages/reason-skia/examples/skia-sdl2/SkiaSdl.re, src/Core/Window.re, src/Core/WindowCreateOptions.re
This change adds an option when creating a window to determine the acceleration strategy:
- `Auto` - let the platform decide whether to create a hardware or software renderer. Usually this will default to hardware if available.
- `ForceHardware` - only allow hardware-accelerated renderers
- `ForceSoftware` - only allow software-accelerated renderers
The motivation for this change comes from investigating https://github.com/onivim/oni2/issues/2225 https://github.com/onivim/oni2/issues/1185 - it seems that, in some multiple-display cases, there may not be a hardware-accelerated renderer available. 
In that case, Onivim fails to start (`no pixel format available`) - because when it queries the available renderers, there is none matching a hardware-supported OGL context.
This can also allow …
=> feat(window): Add option for choosing acceleration strategy

bench.esy.lock/index.json, doc.esy.lock/index.json, esy.lock/index.json, examples.esy.lock/index.json, js.esy.lock/index.json, package.json, test.esy.lock/index.json
Like #985 , this fixes another failure blocking the windows build - freetype2 was also dependent on CMake.
Manifests as another windows build failure on Onivim nightly/master:
```
error: build failed with exit code: 1
build log:
INSTALL: /cygdrive/c/Users/VssAdministrator/.esy/3______________________________________________________/s/esy_freetype2-2.9.1007-dbc259b7
error: command failed: "bash" "-c" "./esy/configure-windows.sh" (exited with 127)
esy-build-package: exiting with errors above...
building esy-freetype2@2.9.1007
esy: exiting due to errors above
```
We actually don't use freetype2 at all on Windows, anymore, as Skia uses DirectWrite API - so to unblock the builds, this picks up https://github.com/esy-packages/esy-freetype2 to remove this usage of cmake on Windows.
=> fix(windows): Remove freetype2 + another usage of cmake build on Windows

src/UI_Hooks/Tick.re, src/UI_Hooks/Tick.rei, test/UI/HooksTest.re
As reported by @lessp on Discord, this fixes an issue where the tick hook would always execute the initial callback instead of updating with the latest given to it. The fix is to store the callback in a ref, and call that instead of calling the closed over callback directly.
Technically this is a breaking change for code relying on the behavior that the callback goes stale. That seems highly unlikely though, at least intentionally.
=> fix(hooks): tick callback staleness

src/UI_Hooks/Effect.rei, src/UI_Hooks/Reducer.rei, src/UI_Hooks/State.rei
The type signatures for the hooks are quite hard to read.
Especially since most parts of it are abstracted away by the brisk-reconciler.
This change makes it easier to discover how to use the common hooks.
=> add usage example for hooks

examples/Hello.re, packages/reason-skia/examples/skia-cli/SkiaCli.re, packages/reason-skia/src/Skia.re, packages/reason-skia/src/Skia.rei, packages/reason-skia/src/wrapped/bindings/SkiaWrappedBindings.re, src/UI/ImageNode.re
__Issue:__ If no width or height are specified (ie, `<Image src="some-image.png />`), the image won't render.
__Fix:__ When no width / height is set, use the image dimensions as the default.
This also wires up the `Skia.Image.width` / `sk_image_get_width` and `Skia.Image.height`/ `sk_image_get_height` APIs
=> fix(image): Use the image size as the default width/ height if none specified

packages/reason-skia/examples/skia-cli/SkiaCli.re, packages/reason-skia/src/Skia.rei, packages/reason-skia/src/wrapped/bindings/SkiaWrappedBindings.re, src/UI/ViewNode.re
__Issue:__ If a `boxShadow(...)` style was set on a node, and then turned off later, the box-shadow would continue to be shown.
__Defect:__ When `boxShadow(..)` is set - we add an image filter onto the `Skia.Paint.t` owned by the node. This is stateful - if we don't do anything, the box shadow image filter will continue to be applied.
__Fix:__ Turn off the image filter when we don't need it anymore.
This also moves the box-shadow rendering to occur before the border and interior elements are painted. Without this, the box-shadow would be rendered along with the interior element, which would actually draw part of the shadow over the border. I think a better flow would be to draw the interior element first w/ a shadow, and _then_ the borders - but right now, we use the borders to calculate …
=> fix(box-shadow): Toggling box-shadow style had no effect

src/UI/Style.re
The `opacity` style option was removed in #540 , in trying to factor to semantic components. However, since we don't have that yet (dependent on some larger refactorings, as discussed in #489 ) - we should bring this back.
I'd prefer to use a more semantic component like `<Opacity />`, however, in the current design, that can impact layout, as every primitive has an associated layout node.
=> feat(style): Bring back `opacity` style

examples/CanvasExample.re, packages/reason-skia/src/Skia.re, packages/reason-skia/src/Skia.rei, packages/reason-skia/src/wrapped/bindings/SkiaWrappedBindings.re, src/Draw/CanvasContext.re
This adds supporting for creating new GPU-backed or CPU-backed surfaces that we can render to, cache, and re-draw later - adding a new method `createLayer` and `drawLayer` on the `CanvasContext`.
This lets us create a layer from an existing `CanvasContext.t`:
```
let layer =
CanvasContext.createLayer(
~width=128l,
~height=128l,
canvasContext,
);
```
... then draw to it:
```
CanvasContext.drawCircle(
~x=32.,
~y=32.,
~radius=16.,
~paint,
layer,
);
```
Then, we can draw the layer on the current canvas:
```
// And then draw the layer a bunch of places!
CanvasContext.drawLayer(~layer, ~x=300., ~y=300., canvasContext);
CanvasContext.drawLayer(~layer, ~x=264., ~y=264., canvasContext);
CanvasContext.drawLayer(~layer, ~x=264., ~y=300., canvasContext);
CanvasContext.drawLayer(~layer, ~x=300., …
```
=> feat(api): CanvasContext - Add createLayer / drawLayer methods

src/UI/ViewNode.re
__Issue:__
When using rounded borders, even though we set the anti-alias property on the border paint object, we can still end up with jagged edges:
__Defect:__
The inner-rounded rectangle wasn't getting anti-aliasing applied, so jagged edges could still sneak through.
__Fix:__
Set anti-alias on the view node paint as well - this smooths out the edge, which is visually superior:
=> fix(rendering): Aliasing in rounded borders

src/Font/FontCache.re, test/Font/FontCacheTest.re
__Issue:__ While working on https://github.com/onivim/oni2/pull/2563, I observed a hang in the editor some emojis, like the 'heart on fire' emoji:
```
2764 FE0F 200D 1F525                                   ; fully-qualified     # ❤️‍🔥 E13.1 heart on fire
```
From these cases: https://unicode.org/Public/emoji/13.1/emoji-test.txt
__Defect:__ We use a counter to break cycles in the font-fallback resolution strategy (`attempts`), so that we don't get in an infinite loop when we shape, fallback to a font, and then try shaping again. 
However, in this case, we had a hole spanning multiple unicode characters - the heart (`2764`) would resolve correctly, but then the modifiers would not discover a fallback font. In this case, we were resetting the `attempts` counter, and would fail to completely …
=> fix(font-fallback): Hang when trying to shape 'flaming heart' emoji

azure-pipelines.yml, examples/AnalogClock.re, examples/GameOfLife.re, examples/Hello.re, examples/SpringExample.re, examples/Stopwatch.re, src/Core/Tick.re, src/UI_Components/Input.re, src/UI_Components/ScrollView.re, src/UI_Components/Ticker.re, src/UI_Components/Ticker.rei, src/UI_Hooks/Revery_UI_Hooks.re, src/UI_Hooks/Spring.re, src/UI_Hooks/Tick.re, src/UI_Hooks/Tick.rei, src/UI_Hooks/Timer.re, test/Core/TickTest.re, test/UI/HooksTest.re
In Onivim, there is a case where we are stuck rendering in a loop, every frame (which will peg the CPU) - based on the trace logs that I've seen, it looks like a timer is constantly running - likely related to an animation, or a hook that isn't disposed properly.
This adds additional tracing for animations and timers, such that when the app is running with trace logging enabled, it will output the various named timers that are active - hopefully giving us enough information to get to the next round of fixes.
=> perf(diagnostics): Add naming for timers, add trace logging

src/UI_Hooks/Spring.re
__Issue:__ When the spring hook is used, and the enabled flag is toggled, there can be a 'bounce' when the enabled flag is set back to true.
__Defect:__ The spring is only tracking positions when enabled - so if the position changes while the spring is disabled, the spring will bounce from the last position set while enabled, to the current position.
__Fix:__ When the spring is disabled, always set the current position to the target.
=> fix(hooks): Spring - bug when active is toggled

packages/reason-skia/src/config/discover.re
Currently `reason-sdl2` uses the static version while skia uses `-lSDL2` this makes the binary link to SDL2 both dynamically and statically. This is a bug on iOS
=> use static libSDL2.a on skia

src/index.mld
This updates the doc sidebar links so they all point a valid URL.
I noticed the [deployed docs](https://www.outrunlabs.com/revery/api/revery/index.html) seem to be a bit behind and some sidebar links point to 404s.
`esy '@doc' run` and click all sidebar links
=> fix(docs): update sidebar links

packages/reason-sdl2/src/sdl2.re, packages/reason-sdl2/src/sdl2_wrapper.cpp, src/Core/Window.re, src/Core/Window.rei, src/Native/config/discover.re
Since macOS Big Sur changes the size of the titlebar by default, it can lead to things looking kind of strange when you roll your own titlebar (like in Oni). This adds an API to get the size of the titlebar from Cocoa itself, so we don't have to make guesses from the version of macOS or something like that.
=> feat(macOS): add API to get titlebar size

src/Native/cocoa/ReveryAppDelegate.c
This addresses onivim/oni2#2705. Before we were needlessly setting the notification delegate on start, which would prompt the user if they wanted to allow notifications. Now the prompt is shown on first attempt at showing notifications.
=> fix(notifications): remove startup prompt on macOS

packages/reason-sdl2/src/sdl2_wrapper.cpp
__Issue:__ I had observed a new, intermittent crash in Onivim 2 when running on Windows. It was a pretty obscure crash, because it only reproduced with `esy run -f`, and not with `esy run` or `esy run -f --trace`. This suggested it was likely a GC / FFI issue.
After spending time bisecting, and checking new changes to our C FFI, I realized it went fairly far back... and I had just added a second monitor to my Windows machine. I realized if I unhooked the new monitor, it no longer reproduced. I suspected it may have to do with the FFI relating to the SDL_GetDisplay* functions - so I took a pass over it, and realized we were missing some `Val_int`s when passing the display width, height, and refresh rate.
This seems innocuous, but without a proper tag bit …
=> fix(sdl2): Fix FFI for Display* functions

src/Native/ReveryNSObject.c, src/Native/dune
In trying to bring Onivim up-to-date with latest Revery, this link error was being hit when running inline tests:
```
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
Error: Error during linking
ocamlopt src/Feature/Layout/.Feature_Layout.inline-tests/run.exe (exit 2)
(cd /Users/runner/work/1/s/_esy/default/store/b/oni2-a5340e6c/default && /Users/runner/.esy/3__________________________________________________________________/i/ocaml-4.10.0-f28f0ffe/bin/ocamlopt.opt -w -24 -g -o src/Feature/Layout/.Feature_Layout.inline-tests/run.exe -linkall /Users/runner/.esy/3__________________________________________________________________/i/opam__s__easy_format-opam__c__1.3.2-b4cb22c6/lib/easy-format/easy_format.cmxa …
```
=> fix(osx): Link failure in Onivim

examples/Examples.re, src/Core/Environment.re, src/Core/Environment.rei, src/Core/Window.re, src/Font/FontFamily.re, src/Native/Environment.re, src/Native/ReveryCocoa.h, src/Native/ReveryMac.h, src/Native/config/discover.re, src/Native/dune, src/Native/environment.c, src/Native/environment_mac.c, src/UI_Components/Input.re, src/UI_Components/ScrollView.re
This restructures the `Revery_Native.Environment.getOS` function and the `os` type to include the operating system version on macOS. The main change is that the `Mac` variant now contains three constructors: `Mac(major, minor, bugfix)`
I plan on extending this to other OS's as well (i.e. Linux could contain the kernel version (same format: major, minor, bugfix), Windows could use [`RtlGetVersion`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-rtlgetversion?redirectedfrom=MSDN), etc.)
This is immediately to fix the problem with differing design constraints on different macOS versions in onivim/oni2#2876
=> feat(environment): macOS version

src/Core/Environment.re, src/Core/Environment.rei, src/Core/Window.re, src/Font/FontFamily.re, src/Native/Environment.re, src/Native/ReveryLinux.h, src/Native/dune, src/Native/environment.c, src/Native/environment_linux.c
This extends #1030 to add the same sort of information on Linux. Now the constructor has four arguments: `Linux(kernel, major, minor, patch)`.
=> feat(environment): add kernel version info on Linux

src/Core/Environment.re, src/Core/Environment.rei, src/Core/Window.re, src/Font/FontFamily.re, src/Native/Environment.re, src/Native/ReveryWindows.h, src/Native/dune, src/Native/environment.c, src/Native/environment_windows.c
Extends both #1030 #1031 to include the version information on Windows. Now the constructor looks like `Windows({major: int, minor: int, build: int})`
=> feat(environment): add version information on Windows

examples/Examples.re, examples/NativeIconExample.re, src/Core/Window.re, src/Core/Window.rei, src/Native/ReveryCocoa.h, src/Native/Revery_Native.re, src/Native/Window.re, src/Native/dune, src/Native/window.c, src/Native/window_cocoa.c
This adds a function in a newly created `Revery_Native.Window` and in `Revery_Core.Window` to mark a window as having unsaved work. All this means as of now is that on macOS, the exit button has a little dot in it, i.e.:
This would be a nice little thing to add to Oni, I think 😃
=> feat(window): add function to set unsaved work

packages/reason-sdl2/src/sdl2_wrapper.cpp
__Issue:__ Mouse gestures could potentially cause a crash - ie, https://github.com/onivim/oni2/issues/2919
__Defect:__ In our SDL2 hit test callback, there was an `CAMLparam` and `CAMLlocal` without a matching `CAMLreturn` - breaking the OCaml GC rules. This issue had been around for awhile, but it seems that the extra allocation via wrapping in a caml-managed value helped expose it (https://github.com/revery-ui/revery/commit/5fe4207630eb392d4882fe0f2853bf5f7a907b01)
__Fix:__ Add `CAMLreturnT` to properly wrap the function for the GC
=> fix(windows): HitTest - Fix missed CAMLreturn in hit test function

src/Native/dialog.c
__Issue:__ A crash in Onivim 2 was discovered - there could be crashes in notification handlers triggered by opening a dialog - https://github.com/onivim/oni2/pull/2967
__Defect:__ The notification handlers expect that the runtime is not acquired when they are called, however, there was a case in `runModal` that could trigger notification callbacks while the runtime is acquired
__Fix:__ Release / acquire the runtime around `runModal`
=> fix(osx): Add release/acquire around dialog, since it may trigger callbacks

examples/NativeMenuExample.re, src/Native/Menu.re, src/Native/Menu.rei, src/Native/ReveryCocoa.h, src/Native/menu.c, src/Native/menu_cocoa.c
I totally forgot this in the original menu PR, but @bryphe mentioned it in onivim/oni2#2969.
This just adds `Menu.Item.createSeparator`, which creates a separator item.
On macOS, it looks like this:
=> feat(menu): add more menu item features

examples/NativeMenuExample.re, src/Native/Menu.re, src/Native/Menu.rei, src/Native/cocoa/ReveryMenuItemTarget.c
__Issue:__ In Onivim, when pressing a keyboard shortcut for a menu item, the command gets triggered twice - once via the input handler, and once via the menu callback.
From the menu callback, currently, we don't know whether this came from a keyboard command (which can be ignored, since the keyboard-input pipeline handles it), or if it came from a click / other gesture, in which case we should run it.
__Fix:__ Add a flag to indicate if this callback is due to a keypress or not.
=> fix(OSX): Add flag to indicate if menu item is from key press or not

examples/Examples.re, examples/WavFilePlaybackExample.re, packages/reason-sdl2/src/sdl2.re, packages/reason-sdl2/src/sdl2_wrapper.cpp
After seeing it mentioned in the roadmap, [this issue](https://github.com/revery-ui/revery/pull/555), and wanting it for my own personal Revery project, I added some WAV file playback support.
The interface exposed is a fairly straightforward mapping to a subset of SDL's Audio API. If we want to expose more of the SDL Audio API or would like to work on a higher-level Revery Audio API, I'd be happy to help out there.
Example Usage:
```re
open Revery.Sdl2.Audio;
/* 1. Load the WAV file spec and audio buffer */
let (desiredSpec, buf, len) =
switch (Wav.load("audio.wav")) {
| Ok(data) => data
| Error(err) => failwith(err)
};
/* 2. Open the audio device */
let (device, _obtainedSpec) =
switch(Device.open_(None, false, desiredSpec, Device.AllowedChanges.none)) {
| Ok(data) => data
| Error(err) …
```
=> feat(audio): Add Wav File Playback to SDL

src/Core/Window.re, src/Core/WindowCreateOptions.re
Passing the `Undefined` variant to SDL allows the OS to choose the window position, which seems preferable to picking a location (`Absolute`) or spawning right in the middle of the desktop, across my two monitors (`Centered`).
Works fine from my testing.
Cool project btw.
=> Allow '`Undefined' WindowCreateOption for initial window position

examples/Examples.re, src/Core/App.re, src/Core/App.rei, src/Core/Event.re
Implements the API change discussed in https://github.com/onivim/oni2/issues/3270
I decided to make a `Fanout` submodule of Event to represent "events with return values", but am very open to alternative structures. It seemed unnecessary to add another type paramater for `Event.t` when it's almost always going to be `unit`.
Since this changes the onBeforeQuit signature anyway, I included the exit code since it seems like that might be useful, but I don't have a specific use case in mind.
I didn't make it backwards compatible. It would be possible by instead adding a new `onBeforeQuitFanout` (or something) function that exposes the ability to suppress the response, but I don't know what your plans are in general for backwards compat, so I went with the simplest version first.
=> onBeforeQuit: allow subscribers to prevent immediate quit

src/UI/TextNode.re
__Issue:__ If `textOverflow(Ellipsis)` is specified without a `width(..)` style, it is ignored.
__Fix:__ Allow `textOverflow(Ellipsis)`, using the available node width from` flex`, if `width(..)` style is not specified.
=> fix(text): Allow ellipsis style w/o needing a width property

src/Core/Window.re
__Issue:__ Came from https://github.com/onivim/oni2/issues/3349 - the centering strategy implemented in https://github.com/revery-ui/revery/commit/08c21312e21f02dd33a074c0d9e67a46b4a9d381 does not handle multi-monitor setups well (it will place the application window in between multiple monitors, if there are 2)
__Fix:__ Just use SDL2's centering strategy, which will center on the relevant monitor based on where the application was started
=> fix(window): Use SDL2's centering strategy for create window

packages/reason-harfbuzz/src/config/discover.re
This fix reason-harfbuzz build when doing Linux -> Android / iOS, this allows revery to cross compile with less patches, almost zero.
Same setup of the other files, we should definitely abstract this, but I'm lazy.
=> fix(android): build of reason-harfbuzz on Android

src/Native/dialog_cocoa.c
From https://github.com/onivim/oni2/issues/3519
__Issue:__ When selecting a folder on OSX with Unicode characters, Revery crashes.
__Defect:__ We were converting the returned string using:
```
cStringUsingEncoding:NSASCIIStringEncoding
```
That API returns `NULL` if the string cannot be losslessly encoded in the target format. In the case of a folder with Unicode characters, this API would return null, and the API was assuming that we'd always get a valid string.
__Fix:__ Two fixes:
1) Use UTF-8 encoding instead of ASCII, so that the API can handle Unicode
2) Handle the NULL case more reliably - if there happens to be a folder we can't convert, don't segfault, skip it.
=> fix(osx): Crash when selecting a UTF-8 folder name

examples/InputExample.re, src/Native/Input.re, src/Native/Input.rei, src/Native/ReveryCocoa.h, src/Native/input.c, src/Native/input_cocoa.c
One thing I've missed using Oni as my daily driver is the Emoji picker that is usually triggered by <kbd>Edit</kbd> -> <kbd>Emoji & Symbols</kbd>. This binds to that in `Revery_Native.Input`.
https://user-images.githubusercontent.com/4527949/119004996-0b713e00-b95d-11eb-8535-5f4be97e505f.mov
=> feat(native): add `Input.openEmojiPanel` on macOS

packages/reason-sdl2/src/sdl2_wrapper.cpp
__Issue:__ From investigating https://github.com/ocaml/ocaml/issues/10422 - it looks like there are some uses of `caml_acquire_runtime`/`caml_release_runtime` that are actually unsafe - some callbacks, like the log or hit test callbacks, can actually be dispatched from these in certain platforms.
__Fix:__ Remove these unsafe release/acquire pairs around the SDL2 functions that can dispatch events.
=> fix(sdl2): Remove some unsafe acquire/release calls

src/Native/utilities.c
__Issue:__ In Onivim 2, after removing the acquire/release runtime calls in https://github.com/revery-ui/revery/pull/1072, I saw the native menu was crashing
This actually reproduces in the example app in a couple ways:
- Clicking on a native menu item
- Clicking on a native button
__Defect:__ The native menu callbacks assume the runtime will be released, but that's not the case anymore after #1072 
__Fix:__ Remove the release/acquire runtime pairs in the callback helper
=> fix(osx): Fix acquire/release runtime OSX callbacks

packages/reason-sdl2/src/sdl2.re, packages/reason-sdl2/src/sdl2_wrapper.cpp
This seems to consistently work now (after #1072), and here is why I think that's the case:
Before, we would release the runtime lock before flushing events. These events would include things like mouse clicks, keyboard input, **window resizes**, etc. This meant that in the old patch, *most* resizes would require us to acquire the runtime lock since they were being "committed" in an event flush. However, last time we bumped up against a problematic resize: *synchronous* resizes, like `Window.maximize`. In this case, we already had the runtime lock when the event handler is called, so trying to acquire it again caused a deadlock.
*Now* we no longer release the runtime lock on event flushes 🎉. This means that in every case that we resize the window, the runtime lock is already acquired, so …
=> feat(sdl2): bring back continuous resize patch

packages/reason-sdl2/src/sdl2_wrapper.cpp
__Issue:__ Revery / Onivim can crash when starting under wayland.
From Revery, this can be reproduced by running under `sway` and running the example with:
```
SDL_VIDEODRIVER=wayland esy '@examples' run
```
The application will hang after the first couple renders. Same issue as described in: https://github.com/onivim/oni2/issues/3646
__Defect:__ Based on my testing - it seems this is a regression from https://github.com/revery-ui/revery/pull/1077 However, in pulling the callstack from the hanging app, the application is hanging when trying to re-acquire the runtime after calling `SDL_GL_SwapWindows`. My hypothesis is that there is a timing issue - the time where those SDL_AddEventWatcher events are dispatched might be different per platform, and could be being dispatched while the …
=> fix(linux): Fix crash on resize with wayland
