revery-ui/revery

- .ci/esy-build-steps.yml
This avoids failures like in #46
> CI: Add retry for esy install

- package.json
Workaround for https://github.com/esy/esy/pull/692
> Windows - Dependency: Pin cmdliner@1.0.2

- src/Math/BoundingBox2d.re
- src/Math/Revery_Math.re
- test/Math/BoundingBox2dTests.re
- test/Math/Tests.re
Add a `BoundingBox2d` - an implementation of an axis-aligned bounding box that supports being transformed, for help with the hit testing.
> Hit-testing: Add BoundingBox2d

- .ci/azure-pipelines.yml
- .ci/publish-build-cache.yml
- .ci/restore-build-cache.yml
- .ci/use-node.yml
From esy-ocaml/esy-ci-scripts#6
> Azure CI: Use faster caching strategy

- src/UI/Mouse.re
- src/UI/Mouse.rei
- test/UI/MouseTest.re
> Fix #126 - Initial Mouse Capture API

- esy.lock/index.json
- esy.lock/opam-override/ocaml-migrate-parsetree.1.1.0/files/ocaml-migrate-parsetree.1.1.0.patch
- esy.lock/opam-override/ocaml-migrate-parsetree.1.1.0/package.json
- package.json
- src/Core/App.re
- src/Core/Window.re
__Issue:__ Clicking the 'x' button on our sample apps does nothing
__Defect:__ We're not checking the window close flag (`glfwShouldWindowClose`) and acting on it.
__Fix:__ Filter the windows that should close, destroy them, and stop the app if all windows are closed.
__TODO:__
> Bugfix - Sample app windows don't close when clicking 'x'

- examples/Border.re
- examples/dune
- src/Geometry/Revery_Geometry.re
- src/Geometry/Triangle.re
- src/UI/Assets.re
- src/UI/Style.re
- src/UI/ViewNode.re
> [WIP] Add border styles & triangle primitives

- Revery_UI_Components.opam
- examples/Autocomplete.re
- examples/Bin.re
- examples/Border.re
- src/Revery.re
- src/UI_Components/Clickable.re
- src/UI_Components/Revery_UI_Components.re
- src/UI_Components/dune
- src/dune
We're almost to the point where we can start really building out our palette of cross-platform components! 🎉 
This creates a `Revery.UI.Components` module, with an initial start `<Clickable />` component.
This will be a place where we can build out more components - `<Button />`, `<Slider />`, `<TextInput />`, `<Label />` - out of the primitives + other components.
> Start module for 'Revery.UI.Components'

- README.md
Closes #132 
Sorry about the line-ending space deletion... that's something I have set in `neovim`.
> Add cmake & ragel notes for Linux users

- src/UI/Primitives.re
- src/UI/UiReconciler.re
Fixes #124.
Fixes #125.
I have tested them locally, but didn't commit any usage in the examples. Happy to do so if needed!
> Add mouse events to text and image primitives

- esy.lock.json
- examples/Boxshadow.re
- examples/dune
- src/Shaders/Shader.re
- src/UI/Assets.re
- src/UI/GradientShader.re
- src/UI/Style.re
- src/UI/ViewNode.re
> Add box shadow property

- src/UI/ViewNode.re
This PR fixes #175. Previously, borders were rendered outside of the computed dimensions of a node. As #175 points out, this was the incorrect way to do things, which caused the hitbox to be incorrect, the node to appear uncentered, and the inside of the node to appear too large when a large border width was used. Big thanks to @bmathews for finding this!
Here's a screenshot of the before/after:
> Move borders into width/height bounding box

- src/UI/Revery_UI.re
Need to bring out a few extra `reactify` methods and make them available from `Revery.UI`.
> API: Expose the context API from Revery.UI

- src/UI/Node.re
- src/UI/Style.re
- src/UI/TextNode.re
- src/UI/UiRender.re
- test/UI/MouseTest.re
- test/UI/NodeTests.re
Will prevent division by 0 crash as mentioned in #180.
> Use float pixel ratio

- README.md
Added new section for WSL with list of required packages.
Added more packages for Linux (Ubuntu 18) instructions.
> Added instructions for Windows Subsystem Linux

- src/UI/Revery_UI.re
- src/UI/UiContainer.re
- src/UI/UiReact.re
- src/UI/UiRender.re
Needed to port the tests for #200
> API: Add internal Container API for testing

- src/Core/App.re
- src/Core/Performance.re
- src/UI/UiReact.re
- src/UI/UiRender.re
Reconciliation performance was removed when switching reconcilers; this brings it back.
> Performance: Profile reconciliation

- README.md
Also use `reason` syntax highlighting
> Run refmt on example

- examples/Hello.re
- examples/Slider.re
- src/UI/Primitives.re
- src/UI/Style.re
An oversight of mine while implementing #215 was converting the image primitive to use the same API :man_facepalming: I completely forgot it existed. This change updates it to match the rest of the primitives
> update image primitive to use new style api

- esy.lock/index.json
- package.json
This picks up @wokalski 's fix for briskml/brisk-reconciler#8 - thank you for the help & fix, @wokalski ! 💯
> Dependency: Upgrade brisk reconciler (commit 7901934)

- README.md
I came across the repo and noticed the small typo error 😕
> Fix a small typo on README.md

- src/UI/Selector.re
- src/UI/Style.re
> Add padding to styles

- examples/Autocomplete.re
This somehow was missed out :thinking:
> Convert autocomplete styles

- esy.lock/index.json
- esy.lock/opam/yojson.1.6.0/opam
- package.json
This picks up a bug fix in https://github.com/briskml/brisk-reconciler/pull/19
> Dependency: brisk-reconciler -> 1c102ab

- src/UI_Components/Slider.re
Following up from a comment in #296 - fixing the Slider to remove the underscores, too. Thanks @saitonakamura for catching this 👍
> Slider: Fix underscores in component

- examples/stubs/example_stubs.js
- package.json
- playground/build.js
- playground/package.json
- playground/src/index.css
- playground/src/index.html
- Fix warning introduced by latest #314 
- Fix path for starting the `http-server`
> Minor tweaks for playground

- esy.lock.json
- examples/DropdownExample.re
- examples/Examples.re
- src/UI/Style.re
- src/UI_Components/Dropdown.re
- src/UI_Components/Revery_UI_Components.re
Fixes #221.
I'm not entirely sure if this is the right approach 😅 , but hope it's a step in the right direction. 
In terms of the API, I'm not sure which approach would be best. Whether to have a Dropdown component with subcomponents as children, like so: 
```jsx
<Dropdown>
<Dropdown.Item value="1" label="one"/>
</Dropdown>
```
Or the current approach where we'd have a Dropdown component and pass items in through props, or perhaps even both?   
I've had a look at the browser's implementation of `select` and found that the width of the select is equal to the longest `option`. The only thing I could think of off the top of my head to achieve something similar is rendering the longest label of all the dropdown items and getting the width of that. 
I'm sure I'm missing a few other things 😅
> Feature/Dropdown Component

- esy.lock/index.json
- package.json
This picks up @zbaylin 's PR to add the `glfwSetWindowIcon` API 🎉
> Dependency: reason-glfw -> 3.2.1018

- src/UI_Components/ScrollView.re
Fixes #346.
@bryphe Let me know what you think :)
> Update scroll bounce logic to use reducer

- playground/src/index.html
Fixed the read-only issue with the revery playground editor
> Fixed Playground: Live-editing code #319

- playground/build.js
> Fix 2 simple errors that occur in build script: `where` not found and `Source and destination must not be the same`

- examples/InputExample.re
- examples/TodoExample.re
- src/Core/Key.re
- src/Core/Key.rei
- src/UI_Components/Clickable.re
- src/UI_Components/Input.re
This PR changes a few things in the Input:
* fixes positioning of the cursor
* adds ability to navigate text with the arrow keys
* autofocus - add the ability to specify autofocus if true the element is immediately in focus
* event - return an event type containing info about the pressed key
> Feature/ refactor input

- bench.esy.lock/index.json
- esy.lock/index.json
- package.json
Pick up a fix for an OOM exception on Windows
> Dependency: reason-fontkit -> 2.4.0

- src/UI_Components/Clickable.re
Are we ok with the fact that clickable should react to left button only?
Fixes #468
> Make clickable react only to left button

- bench.esy.lock/index.json
- doc.esy.lock/index.json
- esy.lock/index.json
- package.json
Picks up a performance fix that significantly reduces memory allocation for effects - thank you @wokalski ! 🚀
> Dependency: brisk-reconciler -> dd933fc

- src/Core/App.re
- src/Core/App.rei
- src/Core/dune
This is a helper API to delegate work to be run on the _main thread_ during our main app loop.
> API: App.runOnMainThread

- examples/Examples.re
- src/Core/Log.re
- src/Core/Revery_Core.re
- src/Core/Window.re
This adds a simple logging API, so that we can include logs from Revery in consuming applications (Onivim 2 is a clear use case for this).
> API: Logging

- src/UI/Mouse.re
- src/UI/Mouse.rei
Addresses https://github.com/revery-ui/revery/issues/581
> Add mouse listeners

- src/Shaders/Shader.re
Fix regression from #589 - missing semicolons in precisions.
> Fix missing semicolon in shader precisions

- src/Core/Window.re
Related to onivim/oni2#791, but this is something that makes sense for Revery applications in general.
> Bugfix: Set minimum window size

- examples/Examples.re
- examples/TodoExample.re
Prettied it up a bit to showcase revery's capabilities better, and got it close to feature parity with the actual TodoMVC. 
Design-wise it's still pretty challenging. I encountered a number of bugs and missing features (which was also partly my intention with this).
> TodoMVC example revamp

- examples/FontsExample.re
- examples/Stopwatch.re
- examples/TodoExample.re
- src/Core/Color.re
- src/Core/Key.re
- src/Core/Key.rei
- src/Core/MouseCursors.re
- src/Core/MouseCursors.rei
- src/Core/Performance.re
- src/Core/Tick.re
- src/Core/Time.re
- src/Core/Time.rei
- src/Core/Vsync.re
- src/Core/Window.re
- src/Core/WindowCreateOptions.re
- src/Font/Discovery.re
- src/Font/Revery_Font.re
- src/Math/BoundingBox2d.re
- src/Math/BoundingBox2d.rei
- test/UI/TestFramework.re
Fixes #635 
I see now that this was probably intended for first-time contributors, but I was on a roll :roller_coaster:
There are still a couple of instances of `show` being used from `reason-sdl2` and `reason-font-manager`.
> Chore: show -> toString

- examples/SpringExample.re
- src/UI/Spring.re
- src/UI/Spring.rei
- src/UI_Hooks/Spring.re
Adds the ability to set the position immediately and to configure the threshold below which it should be considered at rest. Also cleaned up and simplified the hook quite a bit.
> A few improvements to the spring hook.

- src/Core/Window.re
Forgotten about in #555 it seems.
> Fix mouse event hardcoded to left button

- examples/SpringExample.re
Really minor change, but good to have for testing the `setImmediately` function to make sure it works as it should, and to confirm that I've screwed up somewhere else.
> Add width slider to SpringExample for manual control

- bench.esy.lock/index.json
- doc.esy.lock/index.json
- esy.lock/index.json
- js.esy.lock/index.json
- package.json
- test.esy.lock/index.json
Pick up a fix for `AttachConsole` when `STDOUT` is already attached
> Dependency: reason-sdl2 -> 2.10.3014

- examples/Examples.re
`--trace` enables trace logging and `--example Spring` starts with the Spring example.
> Add --trace and --example CLI arguments to example app

- .ci/esy-build-steps.yml
- bench.esy.lock/index.json
- doc.esy.lock/index.json
- esy.lock/index.json
- js.esy.lock/index.json
- js.esy.lock/opam/lambda-term.2.0/opam
- package.json
- test.esy.lock/index.json
Picks up a fix for https://github.com/revery-ui/revery/issues/742
> Dependency: reason-skia -> 6ffd9c7

- bench.esy.lock/index.json
- bench/lib/LayoutBench.re
- bench/lib/NodeUtility.re
- bench/lib/RecalculateBench.re
- doc.esy.lock/index.json
- esy.lock/index.json
- js.esy.lock/index.json
- js.esy.lock/opam/lambda-term.2.0.3/opam
- package.json
- src/Math/BoundingBox2d.re
- src/Math/BoundingBox2d.rei
- src/UI/Node.re
- test.esy.lock/index.json
The 'recalculation' phase of the rendering is an expensive part of our rendering pipeline, and for Onivim, can account for 5-6ms.
The recalculation phase:
- Recalculates the 'local' and 'world' transforms
- Recalculates the bounding box, and the 'clipped' bounding box
These are math-heavy operations. However, the way we are constructing and using these matrices is very expensive and results in significant allocations.
This change adds measurements, so we can evaluate the performance of the `recalculate` method. 
__Before any optimizations:__
```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  BENCHMARK                                                     | …
```
> Perf: Benchmark - recalculate

- bench.esy.lock/index.json
- doc.esy.lock/index.json
- esy.lock/index.json
- js.esy.lock/index.json
- package.json
- test.esy.lock/index.json
Brings in the Arch build failure fix here too
> Dependency: reason-harfbuzz -> 0848520

- src/Font/Revery_Font.re
Move the `measure` API to `Revery_Font`
> API - Font: measure

- .ci/esy-build-steps.yml
- .ci/esy-check-hygiene.yml
- .github/workflows/print_docs_path.js
- .github/workflows/print_esy_cache.js
- .github/workflows/validate-pr.yml
- README.md
- bench.esy.lock/index.json
- bench.esy.lock/opam/cmdliner.1.0.2/opam
- bench.esy.lock/opam/ppx_deriving.4.4.1/opam
- doc.esy.lock/index.json
- doc.esy.lock/opam/cmdliner.1.0.2/opam
- doc.esy.lock/opam/ppx_deriving.4.4.1/opam
- esy.lock/index.json
- esy.lock/opam/cmdliner.1.0.2/opam
- esy.lock/opam/ppx_deriving.4.4.1/opam
- js.esy.lock/index.json
- js.esy.lock/opam/cmdliner.1.0.2/opam
- js.esy.lock/opam/ppx_deriving.4.4.1/opam
- test.esy.lock/index.json
- test.esy.lock/opam/cmdliner.1.0.2/opam
- test.esy.lock/opam/ppx_deriving.4.4.1/opam
This PR enable, GitHub Action for build, lint, auto format code, and push docs. A admin user need to enable GitHub pages.
> Add Github Actions for lint, publish doc, and build.

- bench.esy.lock/index.json
- doc.esy.lock/index.json
- esy.lock/index.json
- js.esy.lock/index.json
- src/Core/Color.re
- src/Core/Color.rei
- test.esy.lock/index.json
Adds `Color.rgb_int` and `Color.rgba_int` to create colors from integers.
> API - Color: Add int apis for creating color

- bench.esy.lock/index.json
- bench.esy.lock/opam/zed.2.0.6/opam
- doc.esy.lock/index.json
- doc.esy.lock/opam/zed.2.0.6/opam
- esy.lock/index.json
- esy.lock/opam/zed.2.0.6/opam
- examples/CanvasExample.re
- js.esy.lock/index.json
- js.esy.lock/opam/zed.2.0.6/opam
- src/Draw/CanvasContext.re
- test.esy.lock/index.json
- test.esy.lock/opam/zed.2.0.6/opam
Expose the `drawPath` API and add to our canvas example:
> API: Canvas - drawPath

- src/UI/Render.re
Just removes an unnecessary variable.
> Remove unnecessary variable

- .github/workflows/validate-pr.yml
I think I have updated all actions and use `restore-keys` feature that allow us to fallback to last valid cache so we don't rebuild all from scratch.
> Update gha actions

- esy.lock/index.json
- esy.lock/opam/conf-pkg-config.1.1/opam
- src/Core/Window.re
- src/Core/Window.rei
Binds to reason-sdl2's `Sdl2.Window.minimize`
> Add minimize function to Window

- examples/Examples.re
- examples/FileDragAndDrop.re
- examples/URLFileOpen.re
- src/Native/ReveryCocoa.h
- src/Native/ReveryGtk.h
- src/Native/ReveryWin32.h
- src/Native/Revery_Native.re
- src/Native/Shell.re
- src/Native/dune
- src/Native/shell.c
- src/Native/shell_cocoa.c
- src/Native/shell_gtk.c
- src/Native/shell_win32.c
Similar to https://www.electronjs.org/docs/api/shell#shellopenitemfullpath
> Native: Add Shell module with openItem function

- src/Core/Window.re
- src/Core/Window.rei
Binds to the new `Sdl2.Window.isFullscreen` in `reason-sdl2`
> Window: Add a convenience `isFullscreen` function

- src/Core/Key.rei
I won't have to change carrot this time --'
> KBS2 - Update Key.rei to match my update on Key.re

- bench.esy.lock/index.json
- bench.esy.lock/opam/dune.2.5.0/opam
- bench.esy.lock/opam/ppx_deriving.4.5/opam
- doc.esy.lock/index.json
- doc.esy.lock/opam/dune.2.5.0/opam
- doc.esy.lock/opam/odoc.1.5.0/opam
- doc.esy.lock/opam/ppx_deriving.4.5/opam
- esy.lock/index.json
- esy.lock/opam/dune.2.5.0/opam
- esy.lock/opam/ppx_deriving.4.5/opam
- js.esy.lock/index.json
- js.esy.lock/opam/dune.2.5.0/opam
- js.esy.lock/opam/js_of_ocaml-compiler.3.6.0/opam
- js.esy.lock/opam/ppx_deriving.4.5/opam
- package.json
- test.esy.lock/index.json
- test.esy.lock/opam/dune.2.5.0/opam
- test.esy.lock/opam/ppx_deriving.4.5/opam
This bumps reason to 3.6.0 in order to fix the pathological formatting behaviour show in the diff below (https://github.com/facebook/reason/issues/1828):
<details><summary>Insane refmt diff</summary><p>
```diff
type pathCommand = [
-    // MoveTo
-    | `M(float, float) // x, y
-    | `m(float, float) // dx, dy
-    // LineTo
-    | `L(float, flaot) // x, y
-    | `l(float, float) // dx, dy
-    | `H(float) // x
-    | `h(flaot) // dx
-    | `V(float) // y
-    | `v(float) // dy
-    // CubicBezierCurve
-    | `C(float, float, float, float, float, float) // x1, y1, x2, y2, x, y
-    | `c(float, float, float, float, float, float) // dx1, dy1, dx2, dy2, dx, dy
-    | `S(float, float, float, float) // x2, y2, x, y
-    | `s(float, float, float, float) // dx2, dy2, dx, dy
-    // …
```
> chore(dependency): reason -> 3.6.0

- examples/TodoExample.re
- src/UI_Components/ClickableText.re
- src/UI_Hooks/Revery_UI_Hooks.re
Adds `Hooks.hover`
Also switches `ClickableText` and `TodoExample` to use it.
> Add hover hook

- src/reason-skia/Skia.re
- src/reason-skia/Skia.rei
- src/reason-skia/wrapped/bindings/SkiaWrappedBindings.re
- src/reason-skia/wrapped/types/SkiaWrappedTypes.re
This adds a few more path drawing primitives, as well as one on canvas to draw a rounded rect.
> feat(skia): add more path drawing primitives

- src/UI_Components/Clickable.re
- src/UI_Components/Clickable.rei
- src/UI_Components/ClickableText.re
This stops weird things like right-clicking on a link opening that link.
> Use Clickable component in ClickableText

- examples/Calculator.re
- src/Core/Key.rei
- src/UI_Components/Input.re
This allows pasting into inputs from the clip board into the current position.
I'd also like to ask for some general feedback. I'd like to add things like 
* <KBD>CTRL-Z</KBD> support
* How much history would we like to keep around?
* Do we want to group inputs similar to what content editables in browser do? E.g. typing one word really fast and hitting the undo shortcut will delete the whole word instead of just the last character. 
* <KBD>CTRL-A</KBD> and selection support
* We probably need to decide on colors for that? Probably just inverting foreground and background color? But how do I get the background color of my parent?
Just some thoughts. I can open individual issues for those.
> allow pasting into inputs

- examples/CanvasExample.re
- examples/skia-cli/SkiaCli.re
- src/reason-skia/Skia.re
- src/reason-skia/Skia.rei
- src/reason-skia/wrapped/bindings/SkiaWrappedBindings.re
- src/reason-skia/wrapped/c/c_stubs.c
- src/reason-skia/wrapped/c/c_stubs.h
- src/reason-skia/wrapped/types/SkiaWrappedTypes.re
Simple 2-stop gradient:
3-stop gradient:
> feat(skia): Linear gradients

- src/Core/Window.re
- src/Core/Window.rei
Binds to SDL2's `SDL_RaiseWindow`, documented here: https://wiki.libsdl.org/SDL_RaiseWindow
> feat(window): bind to SDL2's `raise`

- .ci/esy-build-steps.yml
- scripts/docker/archlinux/Dockerfile
- scripts/docker/centos/Dockerfile
This should improve CI times of Windows.
> update esy to 0.6.6

- examples/SpringExample.re
- examples/TextExample.re
This makes the sliders in the examples actually slideable.
> Fix sliders in examples

- packages/reason-skia/src/Skia.re
- packages/reason-skia/src/wrapped/bindings/SkiaWrappedBindings.re
We were getting memory leaks in Oni2 for this in onivim/oni2#2113. This should fix that.
> fix(skia): add destructor for SkString

- packages/reason-skia/src/Skia.re
This was another oversight on my part 😬. This also leaked in onivim/oni2#2113, this should fix that too.
> fix(skia): add finalizer to `sk_data_from_stream`

- src/UI_Components/Clickable.re
- src/UI_Components/Clickable.rei
Wire up the `onBoundingBoxChanged` that we get from `<View />`
> feat(components): API - Add onBoundingBoxChanged to Clickable

- examples/ScrollView.re
- src/Core/Events.re
- src/Core/Window.re
- src/UI/FileDrop.re
- src/UI/Keyboard.re
- src/UI/Mouse.re
- src/UI/NodeEvents.re
- src/UI/Ui.re
- src/UI_Components/ScrollView.re
- test/UI/MouseTest.re
* Adds data about: `ctrlKey`, `altKey`, `shiftKey`, `guiKey` to mouse events.
* Updates Keyboard data to have `guiKey`
* Fixes Scroll view to have horizontal scroll
* Update ScrollView to Handle horizontal scrool with Shift + MouseWheel.
* Fixed state when was no scroll bars but bounce was working
> Updates to add special keys to mouse/filedrop events

- .ci/esy-build-steps.yml
- .ci/esy-check-hygiene.yml
> refactor(dependency): esy -> 0.6.7

- azure-pipelines.yml
- test/Font/FontCacheTest.re
Check if failure in #1005 is specific to that PR
> test(ci): Unblock linux shaping test failure

- examples/CanvasExample.re
- examples/Examples.re
- packages/reason-skia/examples/skia-cli/SkiaCli.re
- packages/reason-skia/src/Skia.re
- packages/reason-skia/src/Skia.rei
- packages/reason-skia/src/wrapped/bindings/SkiaWrappedBindings.re
- packages/reason-skia/src/wrapped/c/c_stubs.h
- packages/reason-skia/src/wrapped/types/SkiaWrappedTypes.re
- Add API for path effects, which will let us improve diagnostic / squiggly rendering in Onivim
> feat(skia): Add path effect API

- bench.esy.lock/index.json
- doc.esy.lock/index.json
- esy.lock/index.json
- examples.esy.lock/index.json
- js.esy.lock/index.json
- package.json
- test.esy.lock/index.json
Fix skia build issue: https://github.com/onivim/oni2/issues/3494
> refactor(dependency): Skia - remove broken 'common' build dep

- examples/Examples.re
- examples/NativeMenuExample.re
- src/Native/Menu.re
- src/Native/Menu.rei
- src/Native/ReveryCocoa.h
- src/Native/menu.c
- src/Native/menu_cocoa.c
#1072 allows us to do this safely since we never have to acquire the runtime lock 😀 
https://user-images.githubusercontent.com/4527949/119751161-a17afc00-be68-11eb-8738-6ad33858efeb.mov
> feat(menu): add `Native.Menu.displayIn`

- examples/NativeMenuExample.re
- src/Native/Menu.re
- src/Native/Menu.rei
- src/Native/menu.c
- src/Native/menu.h
- src/Native/menu_cocoa.c
This adds a <kbd>CTRL</kbd> modifier and conversion of special keys to the right strings.
> feat(menu): better key equivalent API

- src/UI/Revery_UI.re
Add an API to measure the height of text, given a width + style options
> feat(api): Add 'measureText' API
